"use strict";

module.exports = {
  contextual: {
  "TimeNP|上": ["last / previous", "Used with a time word."],
  "TimeNP|下": ["next / following", "Used with a time word."],
  "TimeNP|個": ["measure word", "Used before this time word."],
  "TimeNP|禮拜": ["week", "Time word."],
  "TimeNP|星期五": ["Friday", "Time word."],
  "TimeNP|次": ["time / occasion", "Used in last time / next time."],
  "DirectionalMotionVP|上": ["up / upward", "Direction in a movement phrase."],
  "CompoundDirectionalMotionVP|上": ["up / upward", "Direction in a movement phrase."],
  "DirectionalMotionVP|落": ["down / downward", "Direction in a movement phrase."],
  "CompoundDirectionalMotionVP|落": ["down / downward", "Direction in a movement phrase."],
  "DirectionalMotionVP|嚟": ["come / toward the speaker", "Movement word."],
  "CompoundDirectionalMotionVP|嚟": ["come / toward the speaker", "Movement word."],
  "DirectionalMotionVP|返": ["return / go back", "Movement word."],
  "CompoundDirectionalMotionVP|返": ["return / go back", "Movement word."],
  "DegreeMannerAdverbial|快": ["quickly / fast", "Tells how the action happens."],
  "DegreeMannerAdverbial|啲": ["a bit / more", "Makes the description stronger or softer."],
  "DiMarkedNP|啲": ["some / these", "Used before a noun."],
  "QuantifiedTimeNP|字": ["five-minute unit", "In this duration expression, each 字 means five minutes."],
  "ApproximateQuantity|度": ["about / approximately", "Makes the preceding quantity approximate."],
  "NeedsContext|唔好食": ["needs context", "Could mean do not eat or not good to eat."],
  "PolarQuestionFrame|咩": ["really? / is that so?", "Sentence-final particle asking a biased yes-or-no question."],
  "PolarQuestionFrame|㗎": ["assertive / currently relevant", "Inner particle in an ordered question cluster; kept as one visible token."],
  "DiscourseParticleFrame|啩": ["probably / perhaps", "Sentence-final particle marking uncertainty about the preceding statement."],
  "DiscourseParticleFrame|喎": ["reportedly / noteworthy", "Sentence-final particle marking broad reportative, noteworthy, reminder, or counterexpectation stance; exact subtype depends on tone and context."],
  "DiscourseParticleFrame|啦": ["please / let's / then", "Sentence-final 啦 marking a directive, suggestion, invitation, or interpersonal closure."],
  "DiscourseParticleFrame|喇": ["now / changed situation", "Sentence-final 喇 marking a new or currently relevant situation; it is separate from perfective 咗."],
  "DiscourseParticleFrame|㗎": ["assertive / currently relevant", "Inner sentence-final particle in an ordered cluster; kept as one visible token."],
  "DiscourseParticleFrame|啫": ["only / just", "Restrictive or minimizing particle inside an ordered cluster."],
  "DiscourseParticleFrame|咋": ["only / that's all", "Restrictive or exhaustive-limit particle inside an ordered cluster."],
  "FocusParticleFrame|得": ["only / just", "Limits the following amount or scalar expression."],
  "FocusParticleFrame|啫": ["only / just", "Marks the visible amount as small or limited."],
  "FocusParticleFrame|咋": ["only / that's all", "Marks the visible amount as the limit."],
  "FragmentQuestion|咩": ["really? / what?", "Reaction question whose claim is understood from context."],
  "ModifiedNP|咩": ["what / what kind of", "Directly modifies the following noun."],
  "ProhibitiveImperative|唔好": ["don't", "Tells someone not to do the following action."],
  "DesiderativeVP|好": ["really / very", "Strengthens the following want expression."],
  "ExperientialQuestion|未": ["yet? / ever?", "Asks whether the experience has happened yet."],
},
  surface: {
  // Authorized Glossika Week 16 hobbies/free-time surfaces.
  "睇戲": ["watch a movie", "Activity phrase."],
  "行山": ["go hiking", "Activity phrase."],
  "游水": ["swim", "Activity phrase."],
  "跑步": ["run", "Activity phrase."],
  "影相": ["take photos", "Activity phrase."],
  "聽歌": ["listen to music", "Activity phrase."],
  "睇書": ["read", "Activity phrase."],
  "打機": ["play video games", "Activity phrase."],
  "煮嘢食": ["cook", "Activity phrase; literally cook food."],
  "唱K": ["do karaoke", "Code-switched activity phrase."],
  "行街": ["go shopping / browse shops", "Conventional activity phrase."],
  "去沙灘": ["go to the beach", "Movement plus destination."],
  "做運動": ["exercise", "Activity phrase."],
  "畫畫": ["draw / paint", "Activity phrase."],
  "踢波": ["play football / soccer", "Activity phrase; exact sport depends on context."],
  "打波": ["play ball", "Activity phrase; exact ball game depends on context."],
  "彈琴": ["play piano / a stringed keyboard instrument", "Activity phrase."],
  "釣魚": ["fish", "Activity phrase."],
  "旅行": ["travel", "Activity phrase."],
  "唱歌": ["sing", "Activity phrase."],
  "睇波": ["watch a game", "Activity phrase; normally a ball game."],
  "瑜伽": ["yoga", "Activity noun."],
  "露營": ["go camping", "Activity phrase."],
  "下棋": ["play chess / a board game", "Activity phrase; exact game depends on context."],
  "行公園": ["walk in the park", "Conventional activity phrase in the supplied lesson."],
  "上個禮拜": ["last week", "Time phrase."],
  "上次": ["last time", "Time phrase."],
  "下次": ["next time", "Time phrase."],
  "下個星期五": ["next Friday", "Time phrase."],
  "上嚟": ["come up", "Movement phrase."],
  "落嚟": ["come down", "Movement phrase."],
  "返嚟": ["come back", "Movement phrase."],
  "返上嚟": ["come back up", "Movement phrase."],
  "快啲": ["quickly / hurry up", "Tells how the action happens."],
  "啲芒果": ["some mangoes", "Noun phrase."],
  "可唔可以": ["can / may", "Asks whether something is allowed or possible."],
  "一個": ["one", "One item with a measure word."],
  "一個故仔": ["one story", "Thing being talked about."],
  "一個蘋果": ["one apple", "Thing being acted on."],
  "第二個": ["another / other one", "A context-supplied choice; the exact reading depends on context."],
  "第二個故仔": ["the second story", "Thing being talked about."],
  "你要記得準時還返啲書": ["you need to remember to return the books on time", "VP complement frame."],
  "記得準時還返啲書": ["remember to return the books on time", "VP complement frame."],
  "呢個": ["this one", "Demonstrative and classifier used as a context-supplied noun phrase."],
},
  construction: {
  TimeNP: ["time phrase", "Says when something happens."],
  DirectionalMotionVP: ["movement phrase", "Shows movement and direction."],
  DurativeVP: ["continuing-state phrase", "Shows that a state continues with 住."],
  PerfectiveDirectionalVP: ["completed movement phrase", "Shows completed movement with a final toward/away direction."],
  ProgressiveDirectionalVP: ["ongoing movement phrase", "Shows movement in progress along a visible path."],
  PotentialDirectionalVP: ["can-move phrase", "Says the movement can follow or reach the visible direction."],
  NegativePotentialDirectionalVP: ["cannot-move phrase", "Says the movement cannot follow or reach the visible direction."],
  RestorativeComplementVP: ["restore-state phrase", "Shows an action restoring a prior or expected state."],
  RepetitiveComplementVP: ["repeat-action phrase", "Shows an action being repeated or resumed."],
  CompoundDirectionalMotionVP: ["movement phrase", "Shows return plus direction."],
  NegatedDirectionalMotionVP: ["negative movement phrase", "Says not to move that way."],
  NegatedVP: ["negative action phrase", "Says that an action does not happen."],
  DegreeMannerAdverbial: ["how phrase", "Tells how the action happens."],
  VocativeAddressTerm: ["address phrase", "Names the person being spoken to."],
  ANotAQuestion: ["positive-or-negative question", "Asks which of two alternatives is true, such as eat or not eat."],
  ModalANotAQuestion: ["modal question", "Asks about wanting, permission, ability, or possibility using A-not-A modal structure."],
  CopularANotAQuestion: ["is-or-isn't question", "Asks whether something is or belongs as stated."],
  ExperientialYesNoQuestion: ["experience question", "Asks whether someone has ever done or experienced something."],
  PolarQuestionFrame: ["biased yes-or-no question", "Asks whether a complete statement is true, often with surprise or doubt."],
  DiscourseParticleFrame: ["particle-marked statement", "Adds one or more visible sentence-final particles to a complete statement."],
  FocusParticleFrame: ["restrictive focus phrase", "Limits a visible amount or scalar expression with only / just."],
  ExistentialClause: ["have / exist clause", "Says that someone has something or that something exists."],
  ExistentialPresentationalClause: ["existential presentation", "Introduces a participant and then states where that participant is."],
  ExistentialQuestion: ["have / exist question", "Asks whether something is present, available, or possessed."],
  ExistentialWhQuestion: ["what exists / what is available question", "Asks what thing or kind of thing is present, available, or possessed."],
  CompletionVP: ["finished-action phrase", "Shows that an action is finished or completed."],
  CompletionQuestion: ["finished-yet question", "Asks whether an action has been completed yet."],
  PerfectiveVP: ["perfective action phrase", "Marks an action as a viewed whole with 咗; context supplies its time interpretation."],
  PostverbalZoPerfectiveVP: ["perfective action phrase", "Marks a visible action + 咗 + overt object as perfective. Time, completion, and discourse interpretation are handled separately."],
  ExperientialVP: ["past-experience phrase", "Shows that someone has done or experienced the action before."],
  ReduplicatedVP: ["light-action phrase", "Repeating the verb makes the action sound brief, light, or casual."],
  CoverbFrame: ["pre-action relation phrase", "Introduces a participant, place, source, or tool before the main action."],
  PostThemeParticipantRelation: ["for / to", "Links the preceding action and thing to a following person. The exact link depends on the verb and context."],
  ReportedSpeech: ["reported speech", "Says what someone said or reported."],
  OpinionStanceFrame: ["opinion frame", "Introduces what someone thinks or feels."],
  ModalVP: ["modal action phrase", "Shows possibility, permission, ability, desire, or obligation before an action."],
  StativePredicate: ["state or quality", "Describes a state or quality."],
  DegreeStativePredicate: ["degree and quality phrase", "Says how strongly a state or quality applies."],
  ActionStativeVP: ["action plus quality phrase", "Links an action-like predicate to a following state or quality."],
  StativeNominalComplement: ["descriptive nominal complement", "Turns a visible description into the complement of is / be."],
  CopularRelationFrame: ["is / relation phrase", "Relates something to a description, identity, or category."],
  ComplementEllipsisFragment: ["context-supplied complement", "Leaves a selected complement or domain understood from discourse."],
  SubjectPredicateClause: ["subject-and-predicate clause", "Says what the subject does, is, or experiences."],
  FragmentQuestion: ["fragment question", "Asks about a context-supplied topic, alternative, or missing item."],
  MannerAdverbialVP: ["manner phrase", "Shows how an action is carried out."],
  QuantityNP: ["quantity noun phrase", "A quantity expression with a visible noun head."],
  MeasureExpression: ["measure expression", "A visible number and unit used to state age, price, area, or length."],
  NominalPredicateClause: ["measure-predicate clause", "States an age, price, area, or length without inserting a hidden copula."],
  QuantifiedClassifierNP: ["counted noun phrase", "A numeral, measure word, and visible noun head."],
  DemonstrativeClassifierNP: ["demonstrative noun phrase", "A phrase such as this one or this story, with a demonstrative, measure word, and noun."],
  OvertHeadDemonstrativeClassifierNP: ["demonstrative-classifier noun phrase", "A phrase with a visible demonstrative, visible measure word, and visible noun, such as 呢本書."],
  HeadlessDemonstrativeClassifierNP: ["headless demonstrative-classifier phrase", "A phrase such as 呢個 or 嗰本 with no visible noun. No missing noun is inserted."],
  QuantifiedTimeNP: ["quantified time phrase", "A time expression quantified by every/each or a numeral."],
  ApproximateQuantity: ["approximate quantity phrase", "A numeral and measure word marked as about or approximately that amount."],
  SourceMotionClause: ["source-motion clause", "Shows a movement beginning from a source place."],
  DiMarkedNP: ["noun phrase", "Uses 啲 before a noun: some / the / these items."],
  AssociativeNP: ["linked noun phrase", "A modifier or possessor joined to a visible noun by 嘅."],
  CoordinatedNP: ["coordinated noun phrase", "Two noun phrases joined by and."],
  ModifiedNP: ["modified noun phrase", "A determiner or modifier plus a visible noun head."],
  NominalHeadSpan: ["noun phrase", "A noun used as a complete noun phrase."],
  MotionGoalVP: ["motion goal", "Movement toward a place or destination."],
  DirectedMannerMotionVP: ["directed movement", "Shows how someone moves along a path or toward a destination."],
  GoalAttainmentMotionVP: ["reached-destination movement", "Shows movement successfully reaching a visible destination."],
  MotionPurposeChain: ["movement for a purpose", "Shows movement followed by the action it is done for."],
  SerialVerbPurposeChain: ["linked action-purpose chain", "Shows visible actions in order, with a later purpose action."],
  PathPhrase: ["path or direction phrase", "Shows the route or direction of movement."],
  LocativeWhQuestion: ["where question", "Asks where someone went or where something happened."],
  LocativePostureVP: ["posture and place", "Says someone is sitting, standing, or lying in a place."],
  LocativePlacePhrase: ["location phrase", "Introduces or states a place."],
  TransitiveVP: ["action phrase", "An action with a thing after it."],
  ProductiveVO: ["action phrase", "An action with a thing after it."],
  ProgressiveVP: ["ongoing action", "Shows an action happening now."],
  LexicalGiveRelation: ["give", "Shows lexical GIVE with two overt participants; only the reviewed baseline receives candidate roles."],
  NegatedExistentialClause: ["no / not have", "Says something is not there or not available."],
  FragmentAnswer: ["short answer", "A short answer whose full meaning comes from context."],
  NegatedExistentialFragment: ["negative existence answer", "A short no / do not have / there is not response whose domain comes from context."],
  FormulaDiscourseUnit: ["set response or social phrase", "A conventional response or social expression used as one discourse unit."],
  MalformedCandidate: ["needs checking", "This line looks incomplete or unusual."],
  ProhibitiveImperative: ["don't-do command", "Tells someone not to do the following action."],
  IdentificationFragment: ["identification phrase", "Points out or identifies the context-supplied item, such as this one."],
  ExperientialQuestion: ["experience question", "Asks whether the experience has happened."],
  DesiderativeVP: ["wanting phrase", "Expresses wanting to do the following action."],
  AcceptabilityANotA: ["okay-or-not question", "Asks whether something is okay, possible, or acceptable."],
  LocativeFragment: ["location fragment", "States a place while the person or thing located there is understood from context."],
  NeedsContext: ["needs context", "Meaning depends on the situation around it."],
  VerbComplementVP: ["verb-complement phrase", "A main verb plus a complement, with an object when present."],
  ResultComplement: ["result phrase", "Says an action reaches or attains a result."],
  ResultComplementVP: ["result-complement phrase", "Shows an action and its visible resulting state."],
  NegativePotentialComplement: ["cannot-result phrase", "Says an action cannot reach or attain the result."],
  ClauseRelationGraph: ["linked clauses", "Two connected Cantonese phrases or clauses."],
  ConditionalClause: ["if-clause", "States the condition for a following result."],
  AcceptabilityClause: ["okay / acceptable", "Says that an action or situation is okay or allowed."],
  IntendedFunctionRelation: ["use or function", "Connects a thing or resource to what it is used for."],
  PassivePermissiveRelation: ["passive or let / allow relation", "Connects a participant, 畀/俾, another participant, and an event while preserving passive-versus-permission ambiguity."],
},
};
