"use strict";

module.exports = [
  ["食飯", { verb: "食", object: "飯", label: "VP", type: "ProductiveVO" }],
  ["煮飯", { verb: "煮", object: "飯", label: "VP", type: "ProductiveVO" }],
  ["摘芒果", { verb: "摘", object: "芒果", label: "VP", type: "ProductiveVO" }],
  ["買嘢", { verb: "買", object: "嘢", label: "VP", type: "ProductiveVO" }],
  ["食嘢", { verb: "食", object: "嘢", label: "VP", type: "ProductiveVO" }],
  ["飲水", { verb: "飲", object: "水", label: "VP", type: "ProductiveVO" }],
  ["寫字", { verb: "寫", object: "字", label: "VP", type: "ProductiveVO" }],
  ["寫名", { verb: "寫", object: "名", label: "VP", type: "ProductiveVO" }],
  ["睇書", { verb: "睇", object: "書", label: "VP", type: "ProductiveVO" }],
  ["聽歌", { verb: "聽", object: "歌", label: "VP", type: "ProductiveVO" }],
  // Authorized Glossika Week 16 activity phrases. PRODUCTIVE_VO preserves visible verb/object children.
  ["睇戲", { verb: "睇", object: "戲", label: "VP", type: "ProductiveVO" }],
  ["跑步", { verb: "跑", object: "步", label: "VP", type: "ProductiveVO" }],
  ["影相", { verb: "影", object: "相", label: "VP", type: "ProductiveVO" }],
  ["打機", { verb: "打", object: "機", label: "VP", type: "ProductiveVO" }],
  ["煮嘢食", { verb: "煮", object: "嘢食", label: "VP", type: "ProductiveVO" }],
  ["唱K", { verb: "唱", object: "K", label: "VP", type: "ProductiveVO" }],
  ["做運動", { verb: "做", object: "運動", label: "VP", type: "ProductiveVO" }],
  ["踢波", { verb: "踢", object: "波", label: "VP", type: "ProductiveVO" }],
  ["打波", { verb: "打", object: "波", label: "VP", type: "ProductiveVO" }],
  ["彈琴", { verb: "彈", object: "琴", label: "VP", type: "ProductiveVO" }],
  ["釣魚", { verb: "釣", object: "魚", label: "VP", type: "ProductiveVO" }],
  ["唱歌", { verb: "唱", object: "歌", label: "VP", type: "ProductiveVO" }],
  ["睇波", { verb: "睇", object: "波", label: "VP", type: "ProductiveVO" }],
  ["下棋", { verb: "下", object: "棋", label: "VP", type: "ProductiveVO" }],
  ["講嘢", { verb: "講", object: "嘢", label: "VP", type: "ProductiveVO" }],
  ["打電話", { verb: "打", object: "電話", label: "VP", type: "ProductiveVO" }],
  ["打籃球", { verb: "打", object: "籃球", label: "VP", type: "ProductiveVO" }],
  ["聽電話", { verb: "聽", object: "電話", label: "VP", type: "ProductiveVO" }],
  ["返學", { verb: "返", object: "學", label: "VP", type: "ProductiveVO" }],
  ["放學", { verb: "放", object: "學", label: "VP", type: "ProductiveVO" }],
  ["瞓覺", { verb: "瞓", object: "覺", label: "VP", type: "ProductiveVO" }],
  ["洗手", { verb: "洗", object: "手", label: "VP", type: "ProductiveVO" }],
  ["曬太陽", { verb: "曬", object: "太陽", label: "VP", type: "ProductiveVO" }],
  ["打麻雀", { verb: "打", object: "麻雀", label: "VP", type: "ProductiveVO" }],
  ["默書", { verb: "默", object: "書", label: "VP", type: "ProductiveVO" }],
  ["炒股票", { verb: "炒", object: "股票", label: "VP", type: "ProductiveVO" }],
  ["發脾氣", { verb: "發", object: "脾氣", label: "VP", type: "ProductiveVO" }],
  ["食意粉", { verb: "食", object: "意粉", label: "VP", type: "ProductiveVO" }],
  ["Book枱", { verb: "Book", object: "枱", label: "VP", type: "ProductiveVO" }],
];
