"use strict";

module.exports = {
  demonstrative: ["specifier", "determiner"],
  wh_determiner: ["wh_specifier", "specifier"],
  head_noun: ["noun_head"],
  time_head: ["time"],
  verb_modifier: ["verb_modifier"],
  ordinal_modifier: ["ordinal_modifier"],
  nominal_modifier: ["np", "topic", "object", "head_noun"],
  degree_manner_head: ["degree_manner_head"],
  degree_particle: ["degree_particle"],
  return_motion_verb: ["return_motion_verb", "movement_verb"],
  m4_negator: ["m4_negator", "negator"],
  topic_or_object: ["topic", "object", "np", "location", "head_noun"],
  opinion_topic: ["topic", "object", "np", "location", "head_noun"],
  vp: ["vp", "action_vp", "main_verb", "movement_verb", "directional_motion_vp", "negated_directional_motion_vp", "predicate", "productive_vo", "experiential_vp", "delimited_vp"],
  predicate: ["predicate", "vp", "stative_predicate", "main_verb", "action_vp", "directional_motion_vp", "negated_directional_motion_vp", "productive_vo"],
  person_np: ["subject", "stance_holder", "co_participant", "recipient"],
  cognition_predicate: ["stance_predicate"],
  stance_marker: ["stance_predicate", "seeming_marker"],
  preference_predicate: ["stance_predicate", "preference_predicate"],
  reported_content: ["comment_predicate", "stative_predicate", "predicate", "vp", "topic_or_object", "np"],
  locative_phrase: ["locative_phrase", "location"],
  comment_predicate: ["comment_predicate", "stative_predicate", "lexicalized_stative_predicate", "negative_lexicalized_stative_predicate", "negated_lexicalized_stative", "negative_lexicalized_stative", "degree_modified_lexical_stative", "degree_stative_predicate", "ordinary_degree_stative_predicate", "ordinary_stative_predicate", "comment"],
  scheduling_quality: ["degree", "stative_predicate", "how"],
  approximation: ["approximation", "how"],
  quantity: ["quantity"],
  scalar_dimension_predicate: ["scalar_dimension_predicate", "ordinary_stative_predicate", "stative_predicate", "comment_predicate"],
  discourse_marker: ["discourse_marker", "focus_adverb"],
  modal: ["modal", "desiderative_modal"],
};
