#!/usr/bin/env node
"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");
const tokenEntries = require("../../../src/runtime-resources/lexicon/token-lexicon");
const reviewed = require("../../../src/runtime-resources/lexicon/token-lexicon/cifu-r1751-2000-reviewed");
const policy = require("../../../src/runtime-resources/lexicon/token-lexicon/cifu-r1751-2000-runtime-policy");
const { buildLexicalAnalysisIndex } = require("../../../src/runtime-resources/lexicon/lexical-analyses");
const root = path.resolve(__dirname, "../../..");
const tokenLexicon = Object.fromEntries(tokenEntries);
const analyses = buildLexicalAnalysisIndex(tokenEntries);
const dynamic = reviewed.buildExplicitAnalyses(tokenEntries);
function cifuRows() { const lines = fs.readFileSync(path.join(root,"data","lexical-frequency","cifu-spoken-top-2000.tsv"),"utf8").replace(/^\uFEFF/,"").trimEnd().split(/\r?\n/); const header=lines.shift().split("\t"); const ix=Object.fromEntries(header.map((n,i)=>[n,i])); return lines.map(line=>{const row=line.split("\t"); return {rank:Number(row[ix.rank]),surface:row[ix.word]};}); }
function bandRowsFromCifu(){return cifuRows().filter((r)=>r.rank>=1751&&r.rank<=2000);} function bandRows(surface){return (analyses[surface]||[]).slice(1).filter((r)=>r.provenance&&r.provenance.source===reviewed.SOURCE);} function readings(surface){return (analyses[surface]||[]).map((r)=>r.jyutping);}
test("ranks 1751-2000 retain all 250 exact Cantonese surfaces",()=>{const rows=bandRowsFromCifu();assert.equal(rows.length,250);assert.equal(new Set(rows.map((r)=>r.surface)).size,250);for(const {surface} of rows)assert.ok(tokenLexicon[surface],surface+": exact runtime surface retained");assert.equal(policy.MANDARIN_ONLY_SURFACES.size,0);});
test("global Cifu exact runtime coverage remains 1999/2000 with only 多少 removed",()=>{assert.deepEqual(cifuRows().filter((r)=>!tokenLexicon[r.surface]),[{rank:1404,surface:"多少"}]);});
test("final authority partition is exactly 143 + 45 + 23 + 37 + 2",()=>{assert.equal(Object.keys(reviewed.PROMOTIONS).length,143);assert.equal(reviewed.MULTI_SURFACES.size,45);assert.equal(reviewed.READING_SPLIT_SURFACES.size,23);assert.equal(Object.keys(reviewed.ALTERNATIVE_SPECS).length,68);assert.equal(reviewed.BLOCKED_ATOMIC_SURFACES.size,37);assert.deepEqual(new Set(reviewed.RESEARCH_REQUIRED_SURFACES),new Set(["山個","猷"]));const sets=[new Set(Object.keys(reviewed.PROMOTIONS)),reviewed.MULTI_SURFACES,reviewed.READING_SPLIT_SURFACES,reviewed.BLOCKED_ATOMIC_SURFACES,reviewed.RESEARCH_REQUIRED_SURFACES];const union=new Set();for(const set of sets)for(const surface of set){assert.ok(!union.has(surface),surface+": class overlap");union.add(surface);}assert.equal(union.size,250);});
test("143 broad rows are typed without flattening richer defaults",()=>{for(const [surface,promotion] of Object.entries(reviewed.PROMOTIONS)){const entry=tokenLexicon[surface];assert.ok(entry,surface+": entry exists");assert.ok(!reviewed.isNeutralLexicalEntry(entry),surface+": broad reviewed row typed");if(entry.provenance&&entry.provenance.source===reviewed.SOURCE&&entry.provenance.kind==="reviewed_lexical_promotion"){assert.equal(entry.label,promotion.label);assert.equal(entry.pos,promotion.pos);assert.equal(entry.syntax,promotion.syntax);}}});
test("held and blocked rows receive no band-specific atomic fact",()=>{for(const surface of [...reviewed.RESEARCH_REQUIRED_SURFACES,...reviewed.BLOCKED_ATOMIC_SURFACES]){const entry=tokenLexicon[surface];assert.ok(entry,surface+": exact surface retained");assert.ok(!dynamic[surface],surface+": no reviewed alternative set");assert.ok(!(entry.provenance&&entry.provenance.source===reviewed.SOURCE),surface+": no band default typing");}});
test("68 alternative surfaces preserve default first and stable nonempty IDs",()=>{assert.equal(Object.keys(dynamic).length,68);const seen=new Set();for(const [surface,rows] of Object.entries(dynamic)){assert.ok(rows.length>=2,surface+": default plus alternatives");assert.equal(rows[0].id,"lex:"+surface+":default");for(const row of rows){assert.ok(row.jyutping,row.id+": nonempty Jyutping");assert.ok(!seen.has(row.id),row.id+": unique");seen.add(row.id);}}});
test("high-risk reading corrections replace rejected packet candidates",()=>{const expected={"拃":"zaa6","校":"haau6","梗":"gang2","第時":"dai6 si4","細妹":"sai3 mui2","黏":"nim4","出邊":"ceot1 bin6","全名":"cyun4 meng2","同樣":"tung4 joeng6","有份":"jau5 fan2","判斷":"pun3 dyun3","兔仔":"tou3 zai2","界定":"gaai3 deng6","紅籌":"hung4 cau2","孭":"me1","偈":"gai2","梳打":"so1 daa2","硬係":"ngaang2 hai6","傾計":"king1 gai2","嘴":"zeoi2","撈":"lou1"};for(const [surface,jyutping] of Object.entries(expected))assert.equal(tokenLexicon[surface].jyutping,jyutping,surface+": default reading");assert.ok(!readings("判斷").includes("pun3 tyun5"));assert.ok(!readings("兔仔").some((j)=>/zi2$/u.test(j)));assert.ok(!readings("界定").includes("gaai3 ding6"));assert.ok(!readings("傾計").includes("king1 gai3"));assert.ok(!readings("撈").includes("lou4"));});
test("critical polyfunctionality and reading splits survive as reviewed",()=>{const has=(surface,pos,jyutping)=>bandRows(surface).some((row)=>row.pos===pos&&(!jyutping||row.jyutping===jyutping));assert.ok(has("校","noun","haau6"));assert.ok(has("校","verb","gaau3"));assert.ok(has("文","noun","man4"));assert.ok(has("文","classifier","man1"));assert.ok(has("文","verb","man6"));assert.ok(has("和","function","wo4"));assert.ok(has("和","verb","wo6"));assert.ok(has("和","verb","wu2"));assert.ok(has("量","verb","loeng4"));assert.ok(has("量","noun","loeng6"));assert.ok(has("傳","verb","cyun4"));assert.ok(has("傳","noun","zyun6"));assert.ok(has("悶","adjective","mun6"));assert.ok(has("悶","verb","mun6"));assert.ok(has("旅遊","verb","leoi5 jau4"));assert.ok(has("旅遊","noun","leoi5 jau4"));assert.ok(has("撈","verb","lou1"));assert.ok(has("撈","verb","laau4"));assert.equal(tokenLexicon["嘴"].pos,"noun");assert.ok(!(analyses["嘴"]||[]).some((row)=>row.pos==="classifier"));});
test("Mandarin-only analyses are absent for retained Cantonese surfaces",()=>{assert.notEqual(tokenLexicon["在"].syntax,"progressive_marker");assert.ok(!(analyses["校"]||[]).some((row)=>row.pos==="classifier"));assert.ok(!(analyses["嘴"]||[]).some((row)=>row.pos==="classifier"));});
test("ranks 1-1750 protected analyses and 多少 exclusion survive",()=>{assert.deepEqual((analyses["住"]||[]).map((r)=>r.id),["lex:住:residence_verb","lex:住:durative_marker"]);assert.equal(tokenLexicon["多少"],undefined);assert.equal(analyses["多少"],undefined);assert.ok((analyses["響"]||[]).some((r)=>r.pos==="coverb"));});
