"use strict";

module.exports = [  // CP021B-LX1: bounded lexical and Jyutping coverage imported from the
  // rendered study-suite audit. These entries add lexical recognition only;
  // they do not create or promote grammar constructions.
  ["閒", { label: "like", jyutping: "haan4", syntax: "stative_predicate availability_state", note: "free / available; retained as the lexical stem in 得閒 and 得唔得閒." }],
  ["得閒", { label: "like", jyutping: "dak1 haan4", syntax: "lexicalized_stative_predicate availability_state", note: "free / available / having spare time." }],
  ["車", { label: "what", jyutping: "ce1", syntax: "vehicle_noun object_np head_noun", classifier_classes: ["vehicle"], note: "vehicle / car." }],
  ["心", { label: "what", jyutping: "sam1", syntax: "body_part_or_abstract_noun head_noun", note: "heart / mind; also the second syllable of 點心." }],
  ["點心", { label: "what", jyutping: "dim2 sam1", syntax: "food_noun object_np head_noun", note: "dim sum." }],
  ["住", { label: "doing", jyutping: "zyu6", syntax: "verb residence_verb_or_durative_marker_homograph", note: "residence verb by lexical default; durative/state marker in constructional or utterance-final contexts." }],
  ["仲", { label: "how", jyutping: "zung6", syntax: "additive_continuative_adverb", note: "still / also / in addition." }],
  ["位", { label: "measure_word", jyutping: "wai2", syntax: "classifier_person polite_person_classifier", note: "polite classifier for people." }],
  ["定係", { label: "func", jyutping: "ding6 hai6", syntax: "alternative_question_connector", note: "or; introduces the second alternative." }],
  ["定", { label: "func", jyutping: "ding6", syntax: "alternative_connector_or_decide_verb_homograph", note: "alternative connector by default; decide/fix before overt aspect in the bounded suite data." }],
  ["時", { label: "when", jyutping: "si4", syntax: "time_noun time_head", note: "time." }],
  ["地鐵", { label: "what", jyutping: "dei6 tit3", syntax: "transport_noun object_np head_noun", note: "MTR / metro." }],
  ["站", { label: "where", jyutping: "zaam6", syntax: "place_noun station_head", note: "station / stop." }],
  ["地鐵站", { label: "where", jyutping: "dei6 tit3 zaam6", syntax: "place_np transport_station", note: "MTR / metro station." }],
  ["句", { label: "measure_word", jyutping: "geoi3", syntax: "classifier_utterance sentence_classifier", note: "classifier for sentences and utterances." }],
  ["痛", { label: "like", jyutping: "tung3", syntax: "stative_predicate pain_state", note: "painful / hurt." }],
  ["星期", { label: "when", jyutping: "sing1 kei4", syntax: "time_noun week_expression", note: "week; combines with day numbers." }],
  ["晝", { label: "when", jyutping: "zau3", syntax: "time_head daypart_morpheme", note: "daytime; bound in 晏晝 / 下晝." }],
  ["下晝", { label: "when", jyutping: "haa6 zau3", syntax: "time_np daypart", note: "afternoon." }],
  ["晏晝", { label: "when", jyutping: "aan3 zau3", syntax: "time_np daypart", note: "noon / afternoon." }],
  ["呢排", { label: "when", jyutping: "ni1 paai4", syntax: "time_np recent_period", note: "recently / these days." }],
  ["排", { label: "when", jyutping: "paai4", syntax: "time_period_head", note: "period / stretch, including 呢排." }],
  ["面", { label: "where", jyutping: "min6", syntax: "location_surface_or_side_noun head_noun", note: "surface / side / face; location use depends on the compound." }],
  ["前面", { label: "where", jyutping: "cin4 min6", syntax: "place_np relative_location", note: "in front / ahead." }],
  ["後面", { label: "where", jyutping: "hau6 min6", syntax: "place_np relative_location", note: "behind / at the back." }],
  ["舒服", { label: "like", jyutping: "syu1 fuk6", syntax: "stative_predicate physical_condition", note: "comfortable / feeling well." }],
  ["工", { label: "what", jyutping: "gung1", syntax: "work_noun object_np head_noun", note: "work / job." }],
  ["口", { label: "what", jyutping: "hau2", syntax: "noun opening_or_mouth head_noun", note: "mouth / opening." }],
  ["入口", { label: "where", jyutping: "jap6 hau2", syntax: "place_np entrance", note: "entrance." }],
  ["出口", { label: "where", jyutping: "ceot1 hau2", syntax: "place_np exit", note: "exit." }],
  ["路口", { label: "where", jyutping: "lou6 hau2", syntax: "place_np road_junction", note: "road junction / intersection." }],
  ["辣", { label: "like", jyutping: "laat6", syntax: "stative_predicate taste_property", note: "spicy / hot." }],
  ["高興", { label: "like", jyutping: "gou1 hing3", syntax: "stative_predicate emotion_state", note: "happy / pleased." }],
  ["認識", { label: "doing", jyutping: "jing6 sik1", syntax: "verb cognition_social_acquaintance transitive_verb", note: "know / become acquainted with." }],
  ["訂", { label: "doing", jyutping: "ding6", syntax: "verb booking_ordering_verb transitive_verb", note: "book / reserve / order." }],
  ["讀", { label: "doing", jyutping: "duk6", syntax: "verb reading_pronunciation_verb transitive_verb", note: "read / pronounce." }],
  ["市", { label: "what", jyutping: "si5", syntax: "place_or_market_noun head_noun", note: "city / market; exact sense depends on compound." }],
  ["市中心", { label: "where", jyutping: "si5 zung1 sam1", syntax: "place_np city_center", note: "city centre." }],
  ["事", { label: "what", jyutping: "si6", syntax: "event_or_matter_noun head_noun", note: "matter / affair / thing." }],
  ["比", { label: "func", jyutping: "bei2", syntax: "comparison_marker coverb", note: "comparison marker 'than'; distinct from 畀 by orthography." }],
  ["搭", { label: "doing", jyutping: "daap3", syntax: "verb transport_use_verb transitive_verb", note: "take / ride (transport)." }],
  ["巴士", { label: "what", jyutping: "baa1 si2", syntax: "transport_noun object_np", note: "bus." }],
  ["號", { label: "func", jyutping: "hou6", syntax: "number_or_date_suffix", note: "number; date or ordinal-like suffix depending on context." }],
  ["救護車", { label: "what", jyutping: "gau3 wu6 ce1", syntax: "vehicle_noun emergency_vehicle object_np", note: "ambulance." }],
  ["埋單", { label: "doing", jyutping: "maai4 daan1", syntax: "verb restaurant_payment_formula", note: "ask for / settle the bill." }],
  ["電視", { label: "what", jyutping: "din6 si6", syntax: "media_noun object_np head_noun", note: "television / TV." }],
  ["普通話", { label: "what", jyutping: "pou2 tung1 waa2", syntax: "language_noun object_np", note: "Mandarin / Putonghua." }],
  ["女", { label: "who", jyutping: "neoi5", syntax: "person_noun female_person", note: "woman / daughter depending on context." }],
  ["馬路", { label: "where", jyutping: "maa5 lou6", syntax: "place_noun road", note: "road / street." }],
  ["飛", { label: "what", jyutping: "fei1", syntax: "ticket_noun colloquial_object_np", note: "ticket (colloquial)." }],
  ["後日", { label: "when", jyutping: "hau6 jat6", syntax: "time_np day_expression", note: "the day after tomorrow." }],
  ["原來", { label: "func", jyutping: "jyun4 loi4", syntax: "discourse_marker realization_marker", note: "as it turns out / originally." }],
  ["暈", { label: "like", jyutping: "wan4", syntax: "stative_or_change_state_predicate physical_condition", note: "faint / dizzy / unconscious." }],
  ["郁", { label: "doing", jyutping: "juk1", syntax: "verb movement_verb", note: "move." }],
  ["一共", { label: "how", jyutping: "jat1 gung6", syntax: "totality_adverb", note: "in total / altogether." }],
  ["開始", { label: "doing", jyutping: "hoi1 ci2", syntax: "verb inception_verb", note: "begin / start." }],
  ["散紙", { label: "what", jyutping: "saan2 zi2", syntax: "money_noun object_np", note: "loose change." }],
  ["碗", { label: "measure_word", jyutping: "wun2", syntax: "classifier_bowl container_classifier", note: "classifier for bowls / bowlfuls." }],
  ["報名", { label: "doing", jyutping: "bou3 meng2", syntax: "verb registration_verb", note: "register / sign up." }],
  ["半", { label: "how", jyutping: "bun3", syntax: "fraction_quantifier", note: "half." }],
  ["新聞", { label: "what", jyutping: "san1 man4", syntax: "information_noun news_noun", note: "news." }],
  ["報紙", { label: "what", jyutping: "bou3 zi2", syntax: "media_noun newspaper_noun", note: "newspaper." }],
  ["容易", { label: "like", jyutping: "jung4 ji6", syntax: "stative_predicate difficulty_scale", note: "easy." }],
  ["意思", { label: "what", jyutping: "ji3 si1", syntax: "abstract_noun meaning_or_intention", note: "meaning / intention." }],
  ["講法", { label: "what", jyutping: "gong2 faat3", syntax: "nominalized_expression wording_noun", note: "way of saying / wording." }],
  ["廣州", { label: "where", jyutping: "gwong2 zau1", syntax: "proper_place city_name", note: "Guangzhou." }],
  ["練", { label: "doing", jyutping: "lin6", syntax: "verb practice_verb transitive_verb", note: "practise / train." }],
  ["詩", { label: "what", jyutping: "si1", syntax: "text_noun pronunciation_drill_item", note: "poem / poetry." }],
  ["史", { label: "what", jyutping: "si2", syntax: "history_noun pronunciation_drill_item", note: "history." }],
  ["星", { label: "what", jyutping: "sing1", syntax: "celestial_noun pronunciation_drill_item", note: "star." }],
  ["巴", { label: "neutral", jyutping: "baa1", syntax: "pronunciation_drill_item lexical_character", note: "pronunciation-drill character 巴." }],
  ["怕", { label: "doing", jyutping: "paa3", syntax: "verb emotion_predicate fear_verb", note: "fear / be afraid." }],
  ["他", { label: "who", jyutping: "taa1", syntax: "written_register_pronoun pronunciation_drill_item", note: "written-register third-person pronoun; spoken Cantonese normally uses 佢." }],
  ["家", { label: "what", jyutping: "gaa1", syntax: "home_family_noun pronunciation_drill_item", note: "home / family." }],
  ["卡", { label: "what", jyutping: "kaa1", syntax: "card_noun pronunciation_drill_item", note: "card." }],
  ["渣", { label: "neutral", jyutping: "zaa1", syntax: "pronunciation_drill_item lexical_character", note: "pronunciation-drill character 渣." }],
  ["叉", { label: "what", jyutping: "caa1", syntax: "utensil_or_fork_noun pronunciation_drill_item", note: "fork / cross." }],
  ["牙", { label: "what", jyutping: "ngaa4", syntax: "body_part_noun pronunciation_drill_item", note: "tooth." }],
  ["門", { label: "what", jyutping: "mun4", syntax: "door_noun head_noun", note: "door / gate." }],
  ["清楚", { label: "like", jyutping: "cing1 co2", syntax: "result_or_stative_predicate clarity_state", note: "clear / clearly." }],
  ["質素", { label: "what", jyutping: "zat1 sou3", syntax: "quality_noun abstract_noun", note: "quality." }],
  ["轉", { label: "doing", jyutping: "zyun3", syntax: "verb direction_change_verb", note: "turn; lexical reading here is zyun3 for physical direction." }],
  ["左", { label: "where", jyutping: "zo2", syntax: "direction_noun_or_modifier", note: "left." }],
  ["右", { label: "where", jyutping: "jau6", syntax: "direction_noun_or_modifier", note: "right." }],
  ["毫", { label: "measure_word", jyutping: "hou4", syntax: "money_subunit dime_unit", note: "ten-cent monetary unit / hou." }],
  ["證件", { label: "what", jyutping: "zing3 gin6", syntax: "document_noun object_np", note: "identity or official document." }],
  ["噃", { label: "particle", jyutping: "bo3", syntax: "sentence_final_particle reminder_realization_particle", note: "sentence-final reminder / realization particle." }],
  ["塞車", { label: "doing", jyutping: "sak1 ce1", syntax: "traffic_event_predicate", note: "traffic jam / be stuck in traffic." }],
  ["救命", { label: "func", jyutping: "gau3 meng6", syntax: "emergency_formula", note: "help! / save me." }],
  ["交通意外", { label: "what", jyutping: "gaau1 tung1 ji3 ngoi6", syntax: "event_noun accident_event", note: "traffic accident." }],
  ["呼吸", { label: "doing", jyutping: "fu1 kap1", syntax: "verb_or_noun breathing_predicate", note: "breathe / breathing." }],
  ["火警", { label: "what", jyutping: "fo2 ging2", syntax: "emergency_event fire_alarm", note: "fire / fire alarm." }],
  ["壺", { label: "measure_word", jyutping: "wu4", syntax: "classifier_pot container_classifier", note: "classifier for pots / a pot." }],
  ["飽", { label: "like", jyutping: "baau2", syntax: "result_or_stative_predicate satiation_state", note: "full after eating." }],
  ["頭痛", { label: "like", jyutping: "tau4 tung3", syntax: "stative_predicate symptom", note: "headache / have a headache." }],
  ["發燒", { label: "doing", jyutping: "faat3 siu1", syntax: "health_state_predicate", note: "have a fever." }],
  ["嗰陣", { label: "when", jyutping: "go2 zan6", syntax: "time_np demonstrative_time", note: "at that time / then." }],
  ["陣", { label: "when", jyutping: "zan6", syntax: "time_or_event_classifier time_head", note: "period / spell / time." }],
  ["藥", { label: "what", jyutping: "joek6", syntax: "medicine_noun object_np", note: "medicine / drug." }],
  ["敏感", { label: "like", jyutping: "man5 gam2", syntax: "stative_predicate sensitivity_or_allergy", note: "sensitive / allergic." }],
  ["困難", { label: "like", jyutping: "kwan3 naan4", syntax: "stative_or_nominal difficulty_state", note: "difficult / difficulty." }],
  ["改", { label: "doing", jyutping: "goi2", syntax: "verb change_verb transitive_verb", note: "change / alter." }],
  ["碼", { label: "what", jyutping: "maa5", syntax: "size_or_code_noun head_noun", note: "size / code / number." }],
  ["色", { label: "what", jyutping: "sik1", syntax: "color_noun head_noun", note: "colour." }],
  ["行山", { label: "doing", jyutping: "haang4 saan1", syntax: "verb activity_predicate", note: "hike / go hiking." }],
  ["焗", { label: "like", jyutping: "guk6", syntax: "stative_predicate weather_property", note: "stuffy / muggy / oppressively hot." }],
  ["第", { label: "func", jyutping: "dai6", syntax: "ordinal_prefix", note: "ordinal prefix." }],
  ["歡迎", { label: "doing", jyutping: "fun1 jing4", syntax: "verb greeting_welcome_verb", note: "welcome." }],
  ["初次", { label: "when", jyutping: "co1 ci3", syntax: "temporal_adverb first_occurrence", note: "for the first time." }],
  ["酒店", { label: "where", jyutping: "zau2 dim3", syntax: "place_np hotel", note: "hotel." }],
  ["早餐", { label: "what", jyutping: "zou2 caan1", syntax: "meal_noun breakfast", note: "breakfast." }],
  ["換", { label: "doing", jyutping: "wun6", syntax: "verb exchange_change_verb transitive_verb", note: "exchange / change." }],
  ["港幣", { label: "what", jyutping: "gong2 bai6", syntax: "currency_noun money_np", note: "Hong Kong dollars / HK currency." }],
  ["匯率", { label: "what", jyutping: "wui6 leot6", syntax: "financial_noun exchange_rate", note: "exchange rate." }],
  ["美國", { label: "where", jyutping: "mei5 gwok3", syntax: "proper_place country_name", note: "United States." }],
  ["中國", { label: "where", jyutping: "zung1 gwok3", syntax: "proper_place country_name", note: "China." }],
  ["工作", { label: "what", jyutping: "gung1 zok3", syntax: "work_noun activity_noun", note: "work / job." }],
  ["附近", { label: "where", jyutping: "fu6 gan6", syntax: "relative_place_expression", note: "nearby / vicinity." }],
  ["銀行", { label: "where", jyutping: "ngan4 hong4", syntax: "place_or_institution_noun bank", note: "bank." }],
  ["先至", { label: "func", jyutping: "sin1 zi3", syntax: "sequence_focus_marker", note: "only then / not until." }],
  ["地方", { label: "where", jyutping: "dei6 fong1", syntax: "place_noun location_np", note: "place." }],
  ["戶口", { label: "what", jyutping: "wu6 hau2", syntax: "account_noun bank_account", note: "account." }],
  ["文件", { label: "what", jyutping: "man4 gin2", syntax: "document_noun object_np", note: "document / paperwork." }],
  ["簽", { label: "doing", jyutping: "cim1", syntax: "verb signing_verb transitive_verb", note: "sign." }],
  ["行程", { label: "what", jyutping: "hang4 cing4", syntax: "schedule_itinerary_noun", note: "itinerary / schedule." }],
  ["乾淨", { label: "like", jyutping: "gon1 zeng6", syntax: "stative_predicate cleanliness_property", note: "clean." }],
  ["垃圾", { label: "what", jyutping: "laap6 saap3", syntax: "waste_noun object_np", note: "rubbish / garbage." }],
  ["亂", { label: "how", jyutping: "lyun6", syntax: "manner_adverb disorderly_manner", note: "randomly / carelessly / in disorder." }],
  ["掉", { label: "doing", jyutping: "diu6", syntax: "verb disposal_verb", note: "throw away; standard-written item in the suite." }],
  ["學費", { label: "what", jyutping: "hok6 fai3", syntax: "money_noun tuition_fee", note: "tuition / school fees." }],
  ["運動", { label: "doing", jyutping: "wan6 dung6", syntax: "activity_noun_or_verb exercise_activity", note: "exercise / sport." }],
  ["鐘", { label: "when", jyutping: "zung1", syntax: "time_unit hour_unit", note: "hour / clock." }],
  ["提醒", { label: "doing", jyutping: "tai4 sing2", syntax: "verb reminder_verb transitive_verb", note: "remind." }],
  ["搵工", { label: "doing", jyutping: "wan2 gung1", syntax: "verb job_search_activity", note: "look for work." }],
  ["轉工", { label: "doing", jyutping: "zyun2 gung1", syntax: "verb job_change_activity", note: "change jobs." }],
  ["估", { label: "doing", jyutping: "gu2", syntax: "verb cognition_guess_verb", note: "guess / suppose." }],
  ["單", { label: "measure_word", jyutping: "daan1", syntax: "classifier_case_order_or_news_item", note: "classifier for cases, orders, or news items." }],
  ["乜", { label: "what", jyutping: "mat1", syntax: "wh_thing colloquial_wh", note: "what." }],
  ["犀利", { label: "like", jyutping: "sai1 lei6", syntax: "stative_predicate degree_evaluation", note: "formidable / intense / impressive." }],
  ["轉車", { label: "doing", jyutping: "zyun2 ce1", syntax: "verb transport_transfer_activity", note: "change vehicles / transfer." }],
  ["海洋公園", { label: "where", jyutping: "hoi2 joeng4 gung1 jyun2", syntax: "proper_place attraction_name", note: "Ocean Park." }],
  ["門票", { label: "what", jyutping: "mun4 piu3", syntax: "ticket_noun admission_ticket", note: "admission ticket." }],
  ["記住", { label: "doing", jyutping: "gei3 zyu6", syntax: "verb cognition_memory_imperative", note: "remember." }],
  ["黃大仙", { label: "where", jyutping: "wong4 daai6 sin1", syntax: "proper_place district_or_temple_name", note: "Wong Tai Sin." }],
  ["節目", { label: "what", jyutping: "zit3 muk6", syntax: "media_or_event_noun program", note: "programme / show." }],
  ["事關", { label: "func", jyutping: "si6 gwaan1", syntax: "cause_connector discourse_connector", note: "because / the reason is." }],
  ["碟", { label: "measure_word", jyutping: "dip6", syntax: "classifier_dish plate_classifier", note: "classifier for dishes / plates." }],
  ["假", { label: "like", jyutping: "gaa2", syntax: "stative_predicate authenticity_property", note: "fake / false." }],
  ["女人街", { label: "where", jyutping: "neoi5 jan2 gaai1", syntax: "proper_place street_name", note: "Ladies' Market / Tung Choi Street." }],
  ["公屋", { label: "where", jyutping: "gung1 uk1", syntax: "housing_place public_housing", note: "public housing." }],
  ["區", { label: "where", jyutping: "keoi1", syntax: "area_noun place_head", note: "district / area." }],
  ["租金", { label: "what", jyutping: "zou1 gam1", syntax: "money_noun rent", note: "rent." }],
  ["申請", { label: "doing", jyutping: "san1 cing2", syntax: "verb application_verb", note: "apply / application." }],
  ["生活費", { label: "what", jyutping: "sang1 wut6 fai3", syntax: "money_noun living_expenses", note: "living expenses." }],
  ["愈來愈", { label: "how", jyutping: "jyu6 loi4 jyu6", syntax: "degree_change_marker", note: "more and more." }],
  ["慳", { label: "doing", jyutping: "haan1", syntax: "verb economize_save_verb", note: "save / economize." }],
  ["搬", { label: "doing", jyutping: "bun1", syntax: "verb relocation_verb", note: "move / relocate." }],
  ["初初", { label: "when", jyutping: "co1 co1", syntax: "temporal_adverb initial_period", note: "at first / initially." }],
  ["習慣", { label: "like", jyutping: "zaap6 gwaan3", syntax: "stative_or_verb habituation_predicate", note: "used to / accustomed / habit." }],
  ["解釋", { label: "doing", jyutping: "gaai2 sik1", syntax: "verb explanation_verb transitive_verb", note: "explain." }],
  ["自然", { label: "like", jyutping: "zi6 jin4", syntax: "stative_predicate naturalness_property", note: "natural." }],
  ["發音", { label: "what", jyutping: "faat3 jam1", syntax: "pronunciation_noun_or_verb", note: "pronunciation / pronounce." }],
  ["聲調", { label: "what", jyutping: "sing1 diu6", syntax: "linguistic_noun tone", note: "tone." }],
  ["日常", { label: "how", jyutping: "jat6 soeng4", syntax: "nominal_modifier everyday_register", note: "everyday / daily." }],
  ["對話", { label: "what", jyutping: "deoi3 waa6", syntax: "speech_noun dialogue", note: "dialogue / conversation." }],
  ["肯定", { label: "like", jyutping: "hang2 ding6", syntax: "stance_predicate certainty", note: "certain / sure / affirm." }],
  ["差", { label: "doing", jyutping: "caa1", syntax: "verb subtraction_or_shortfall_marker", note: "lack / be short of; used in clock expressions." }],
  ["遲", { label: "like", jyutping: "ci4", syntax: "stative_predicate lateness_property", note: "late." }],
  ["肚餓", { label: "like", jyutping: "tou5 ngo6", syntax: "stative_predicate hunger_state", note: "hungry." }],
  ["口渴", { label: "like", jyutping: "hau2 hot3", syntax: "stative_predicate thirst_state", note: "thirsty." }],
  ["銀包", { label: "what", jyutping: "ngan4 baau1", syntax: "object_np wallet_noun", note: "wallet / purse." }],
  ["分別", { label: "what", jyutping: "fan1 bit6", syntax: "abstract_noun difference", note: "difference." }],
  ["Chris", { label: "who", syntax: "latin_proper_name person_np", note: "Latin-script personal name; no Jyutping applicable." }],
  ["Crawford", { label: "who", syntax: "latin_proper_name surname_np", note: "Latin-script surname; no Jyutping applicable." }],
  ["雲吞麵", { label: "what", jyutping: "wan4 tan1 min6", syntax: "food_noun object_np", note: "wonton noodles." }],
  ["咪", { label: "func", syntax: "polysemous_mai_marker", note: "咪 is context-sensitive: prohibitive mai5 before a predicate, but mai6 in several discourse/focus uses." }],
  ["客氣", { label: "like", jyutping: "haak3 hei3", syntax: "stative_or_behavior_predicate politeness_property degree_manner_head", note: "polite / ceremonious; degreeable before 啲 in a scalar adjustment phrase." }],
  ["姓", { label: "doing", jyutping: "sing3", syntax: "verb surname_relation_verb", note: "have the surname / be surnamed." }],
  ["跟住", { label: "func", jyutping: "gan1 zyu6", syntax: "sequence_connector discourse_marker", note: "then / next / following that." }],
  ["麻麻地", { label: "like", jyutping: "maa4 maa2 dei2", syntax: "lexicalized_stative_predicate moderate_evaluation", note: "so-so / mediocre." }],
  ["找", { label: "doing", jyutping: "zaau2", syntax: "verb change_money_verb written_or_regional_form", note: "give change / make change in 找錢; distinct from 搵 'look for'." }],
  ["旺角", { label: "where", jyutping: "wong6 gok3", syntax: "proper_place district_name", note: "Mong Kok." }],
  ["報警", { label: "doing", jyutping: "bou3 ging2", syntax: "verb emergency_report_verb", note: "call / report to the police." }],
  ["受傷", { label: "like", jyutping: "sau6 soeng1", syntax: "result_state_predicate injury_state", note: "injured / sustain an injury." }],
  ["地址", { label: "where", jyutping: "dei6 zi2", syntax: "location_reference_noun address", note: "address." }],
  ["自己", { label: "who", jyutping: "zi6 gei2", syntax: "reflexive_pronoun person_np", note: "self / oneself." }],
  ["籠", { label: "measure_word", jyutping: "lung4", syntax: "classifier_bamboo_steamer container_classifier", note: "classifier for bamboo steamers / baskets." }],
  ["蝦餃", { label: "what", jyutping: "haa1 gaau2", syntax: "food_noun dim_sum_item", note: "shrimp dumpling / har gow." }],
  ["斤", { label: "measure_word", jyutping: "gan1", syntax: "weight_unit classifier_weight", note: "catty / jin, a weight measure." }],
  ["新鮮", { label: "like", jyutping: "san1 sin1", syntax: "stative_predicate freshness_property", note: "fresh." }],
  ["傾", { label: "doing", jyutping: "king1", syntax: "verb conversation_verb", note: "chat / talk." }],
  ["把", { label: "measure_word", jyutping: "baa2", syntax: "classifier_handled_object", note: "classifier for handled objects such as umbrellas." }],
  ["遮", { label: "what", jyutping: "ze1", syntax: "object_np umbrella_noun", note: "umbrella." }],
  ["塞", { label: "doing", jyutping: "sak1", syntax: "verb blockage_or_traffic_jam_predicate", note: "block / be congested." }],
  ["吳", { label: "who", jyutping: "ng4", syntax: "surname_element proper_name_part", note: "surname Ng / Wu." }],
  ["飯前", { label: "when", jyutping: "faan6 cin4", syntax: "time_np meal_relative_time", note: "before a meal." }],
  ["飯後", { label: "when", jyutping: "faan6 hau6", syntax: "time_np meal_relative_time", note: "after a meal." }],
  ["藍色", { label: "like", jyutping: "laam4 sik1", syntax: "color_modifier stative_predicate degreeable", note: "blue / blue-colored." }],
  ["……", { label: "neutral", syntax: "ellipsis_punctuation", note: "ellipsis punctuation; no Jyutping applicable." }],
];
