"use strict";

module.exports = [  // Things / nouns
  ["飯", { label: "what", jyutping: "faan6", syntax: "object_np", classifier_classes: ["food_bowl"], note: "rice / meal" }],
  ["嘢", { label: "what", jyutping: "je5", syntax: "object_np", note: "thing / stuff" }],
  ["水", { label: "what", jyutping: "seoi2", syntax: "object_np liquid drink_object water_noun", classifier_classes: ["liquid_measure"], note: "water; liquid/drink object, not generic food." }],
  ["茶", { label: "what", jyutping: "caa4", syntax: "object_np liquid drink_object beverage_noun", classifier_classes: ["liquid_measure"], note: "tea; drink/beverage object, not generic food." }],
  ["咖啡", { label: "what", jyutping: "gaa3 fe1", syntax: "object_np liquid drink_object beverage_noun", note: "coffee; drink/beverage object." }],
  ["奶", { label: "what", jyutping: "naai5", syntax: "object_np liquid drink_object beverage_noun", note: "milk; drink/liquid object." }],
  ["麵", { label: "what", jyutping: "min6", syntax: "object_np", note: "noodles" }],
  ["菜", { label: "what", jyutping: "coi3", syntax: "object_np", note: "vegetables" }],
  ["肉", { label: "what", jyutping: "juk6", syntax: "object_np", note: "meat" }],
  ["刀", { label: "what", jyutping: "dou1", syntax: "object_np instrument_np", note: "knife; overt resource/instrument noun." }],
  ["煲", { label: "what", jyutping: "bou1", syntax: "object_np instrument_np container_np", note: "pot / cooker; overt resource noun." }],
  ["魚", { label: "what", jyutping: "jyu4", syntax: "object_np", note: "fish" }],
  ["雞蛋", { label: "what", jyutping: "gai1 daan2", syntax: "object_np", note: "egg" }],
  ["蘋果", { label: "what", jyutping: "ping4 gwo2", syntax: "object_np food", semantic: ["food"], note: "apple" }],
  ["芒果", { label: "what", jyutping: "mong1 gwo2", syntax: "food_np object_np", note: "mango; native-speech mango-pickup diagnostic object." }],
  ["書", { label: "what", jyutping: "syu1", syntax: "object_np", classifier_classes: ["book"], note: "book" }],
  ["紙", { label: "what", jyutping: "zi2", syntax: "object_np flat_object_np", classifier_classes: ["flat_object"], note: "paper / sheet of paper; reviewed CP021B theme noun." }],
  ["筆", { label: "what", jyutping: "bat1", syntax: "object_np instrument_np", classifier_classes: ["long_rigid"], note: "pen; can be an instrument in 用 + NP + action frames." }],
  ["筷子", { label: "what", jyutping: "faai3 zi2", syntax: "object_np instrument_np", note: "chopsticks; can be an instrument in 用 + NP + action frames." }],
  ["書包", { label: "what", jyutping: "syu1 baau1", syntax: "object_np", note: "schoolbag" }],
  ["功課", { label: "what", jyutping: "gung1 fo3", syntax: "object_np", note: "homework" }],
  ["歌", { label: "what", jyutping: "go1", syntax: "object_np", note: "song" }],
  ["電話", { label: "what", jyutping: "din6 waa2", syntax: "object_np", classifier_classes: ["machine_device"], note: "telephone" }],
  ["故事", { label: "what", jyutping: "gu3 si6", syntax: "object_np story_np information_content", semantic: ["information_content", "readable_content"], note: "story; added as lexicon/Jyutping cleanup for UI example diagnostics." }],
  ["報告", { label: "what", jyutping: "bou3 gou3", syntax: "object_np document_np", note: "report; reviewed CP021B heavy-theme boundary noun." }],
  ["籃球", { label: "what", jyutping: "laam4 kau4", syntax: "object_np sport_object", note: "basketball; overt object in a preserved CP020 permissive example." }],
  ["戲", { label: "what", jyutping: "hei3", syntax: "object_np media_np", note: "film / show / play" }],
  ["衫", { label: "what", jyutping: "saam1", syntax: "object_np clothing_np", classifier_classes: ["clothing"], note: "clothing / shirt" }],
  ["湯", { label: "what", jyutping: "tong1", syntax: "food_np soup_np", note: "soup" }],
  ["手", { label: "what", jyutping: "sau2", syntax: "body_part_np", note: "hand" }],
  ["覺", { label: "what", jyutping: "gaau3", syntax: "object_in_vo", note: "sleep object in 瞓覺" }],
  ["學", { label: "what", jyutping: "hok6", syntax: "object_in_vo", note: "schooling object in 返學/放學" }],
  ["涼", { label: "what", jyutping: "loeng4", syntax: "object_in_vo", note: "bath object in 沖涼" }],
  ["太陽", { label: "what", jyutping: "taai3 joeng4", syntax: "object_np", note: "sun" }],
  ["麻雀", { label: "what", jyutping: "maa4 zoek3", syntax: "object_np", note: "mahjong / sparrow" }],
  ["股票", { label: "what", jyutping: "gu2 piu3", syntax: "object_np", note: "stocks" }],
  ["脾氣", { label: "what", jyutping: "pei4 hei3", syntax: "object_np", note: "temper" }],
  ["聲", { label: "what", jyutping: "seng1", syntax: "object_np", note: "sound / voice" }],
  ["名", { label: "what", jyutping: "meng2", syntax: "object_np", note: "name" }],
  ["名字", { label: "what", jyutping: "meng2 zi6", syntax: "object_np", note: "name" }],
  ["錢", { label: "what", jyutping: "cin2", syntax: "object_np", note: "money" }],
  ["問題", { label: "what", jyutping: "man6 tai4", syntax: "object_np", classifier_classes: ["general_count"], note: "problem" }],
  ["意粉", { label: "what", jyutping: "ji3 fan2", syntax: "food_np", note: "pasta" }],
  ["薄餅", { label: "what", jyutping: "bok6 beng2", syntax: "food_np", note: "pizza" }],
  ["食物", { label: "what", jyutping: "sik6 mat6", syntax: "food_np", note: "food" }],
  ["菜式", { label: "what", jyutping: "coi3 sik1", syntax: "food_np", note: "dish / cuisine item" }],
  ["特別菜式", { label: "what", jyutping: "dak6 bit6 coi3 sik1", syntax: "food_np", note: "special dishes" }],
  ["枱", { label: "what", jyutping: "toi2", syntax: "object_np location_base", note: "table; nominal location base inside spatial-localizer phrases such as 枱上面" }],
  ["牆", { label: "what", jyutping: "coeng4", syntax: "object_np location_base surface_location_noun", note: "wall; nominal location base inside spatial-localizer phrases such as 牆上面" }],
  ["上面", { label: "where", jyutping: "soeng6 min6", syntax: "place_or_goal spatial_localizer upper_surface_localizer", note: "above / on top / on the surface; combines with a visible nominal location base" }],
  ["消息", { label: "what", jyutping: "siu1 sik1", syntax: "object_np", note: "news / update" }],
  ["主意", { label: "what", jyutping: "zyu2 ji3", syntax: "object_np", note: "idea" }],
  ["好主意", { label: "func", jyutping: "hou2 zyu2 ji3", syntax: "formula_evaluation", note: "good idea" }],
  ["興趣", { label: "what", jyutping: "hing3 ceoi3", syntax: "object_np", note: "interest" }],
  ["意大利", { label: "what", jyutping: "ji3 daai6 lei6", syntax: "modifier_or_place_name", note: "Italy / Italian" }],
  ["意大利餐廳", { label: "what", jyutping: "ji3 daai6 lei6 caan1 teng1", syntax: "restaurant_np", note: "Italian restaurant; place entity, but learner-visible role defaults to what/topic unless used as a location." }],
  ["環境", { label: "what", jyutping: "waan4 ging2", syntax: "object_np", note: "environment / ambience" }],
  ["價", { label: "what", jyutping: "gaa3", syntax: "price_np", note: "price" }],
  ["價錢", { label: "what", jyutping: "gaa3 cin2", syntax: "price_np", note: "price" }],
  ["價位", { label: "what", jyutping: "gaa3 wai2", syntax: "price_range_np", note: "price range / price point" }],
  ["中", { label: "like", jyutping: "zung1", syntax: "modifier_middle", note: "middle / mid-" }],
  ["中等", { label: "like", jyutping: "zung1 dang2", syntax: "stative_predicate", note: "medium / moderate" }],
  ["價錢中等", { label: "like", jyutping: "gaa3 cin2 zung1 dang2", syntax: "compositional_price_evaluation", note: "Compositional source phrase; tokenizer keeps 價錢 + 中等 visible." }],
  ["中等價錢", { label: "what", jyutping: "zung1 dang2 gaa3 cin2", syntax: "compositional_price_np", note: "Compositional source phrase; tokenizer keeps 中等 + 價錢 visible." }],
  ["中價位", { label: "what", jyutping: "zung1 gaa3 wai2", syntax: "compositional_price_range", note: "Compositional price range; tokenizer keeps 中 + 價位 visible." }],
  ["中價", { label: "what", jyutping: "zung1 gaa3", syntax: "compositional_price_category_source_form", note: "Glossika source form; native-speaker alternatives are documented in the lesson note, not preferred in runtime parsing." }],
  ["錢", { label: "what", jyutping: "cin2", syntax: "object_np", note: "money" }],
  ["蚊", { label: "what", jyutping: "man1", syntax: "currency_unit", note: "dollar / Hong Kong dollar unit" }],
  ["時間", { label: "when", jyutping: "si4 gaan3", syntax: "time_np", note: "time" }],

  // v0.5.227: source-audited high-frequency lexical coverage.
  ["線", {"label":"what","jyutping":"sin3","syntax":"object_np","note":"line / string / wire; Cifu spoken top-2000 R1 lexical audit."}],
  ["樹", {"label":"what","jyutping":"syu6","syntax":"object_np","note":"tree; Cifu spoken top-2000 R1 lexical audit."}],
  ["政府", {"label":"what","jyutping":"zing3 fu2","syntax":"organization_np object_np","note":"government; Cifu spoken top-2000 R1 lexical audit."}],
  ["塔", {"label":"what","jyutping":"taap3","syntax":"object_np","note":"tower / pagoda; Cifu spoken top-2000 R1 lexical audit."}],
  ["馬戲", {"label":"what","jyutping":"maa5 hei3","syntax":"object_np","note":"circus; Cifu spoken top-2000 R1 lexical audit."}],
  ["角", {"label":"what","jyutping":"gok3","syntax":"object_np","note":"angle / corner / horn; Cifu spoken top-2000 R1 lexical audit."}],
  ["韻", {"label":"what","jyutping":"wan6","syntax":"object_np linguistic_term_np","note":"rhyme / rime; Cifu spoken top-2000 R1 lexical audit."}],

  // v0.5.227: Cifu spoken top-2000 R2 source-audited lexical coverage.
  ["蛇", {"label":"what","jyutping":"se4","syntax":"object_np animal_np","note":"snake / serpent; Cifu spoken top-2000 R2 lexical audit."}],
  ["葡萄", {"label":"what","jyutping":"pou4 tou4","syntax":"object_np food_np","note":"grape; Cifu spoken top-2000 R2 lexical audit."}],
  ["腰", {"label":"what","jyutping":"jiu1","syntax":"object_np body_part_np","note":"waist / lower back; Cifu spoken top-2000 R2 lexical audit."}],
  ["科技", {"label":"what","jyutping":"fo1 gei6","syntax":"abstract_np domain_np","note":"science and technology; Cifu spoken top-2000 R2 lexical audit."}],
  ["社會", {"label":"what","jyutping":"se5 wui2","syntax":"abstract_np collective_np","note":"society; Cifu spoken top-2000 R2 lexical audit."}],
  ["方面", {"label":"what","jyutping":"fong1 min6","syntax":"abstract_np aspect_np","note":"aspect / respect / field / side; Cifu spoken top-2000 R2 lexical audit."}],
  ["煙", {"label":"what","jyutping":"jin1","syntax":"object_np substance_np","note":"smoke / tobacco / cigarette; Cifu spoken top-2000 R2 lexical audit."}],

  // v0.5.227: Cifu spoken top-2000 R3 noun/place lexical coverage.
  ["萍", {"label":"what","jyutping":"ping4","syntax":"object_np plant_np","note":"duckweed; Cifu spoken top-2000 R3 lexical audit."}],
  ["金字塔", {"label":"what","jyutping":"gam1 zi6 taap3","syntax":"object_np landmark_np","note":"pyramid; Cifu spoken top-2000 R3 lexical audit."}],
  ["農", {"label":"what","jyutping":"nung4","syntax":"abstract_np domain_np","note":"agriculture; Cifu spoken top-2000 R3 lexical audit."}],
  ["情況", {"label":"what","jyutping":"cing4 fong3","syntax":"abstract_np situation_np","note":"circumstances / situation; Cifu spoken top-2000 R3 lexical audit."}],
  ["國旗", {"label":"what","jyutping":"gwok3 kei4","syntax":"object_np artifact_np","note":"national flag; Cifu spoken top-2000 R3 lexical audit."}],
  ["燈塔", {"label":"what","jyutping":"dang1 taap3","syntax":"object_np landmark_np","note":"lighthouse; Cifu spoken top-2000 R3 lexical audit."}],
  ["纜車", {"label":"what","jyutping":"laam6 ce1","syntax":"object_np vehicle_np","note":"cable car; Cifu spoken top-2000 R3 lexical audit."}],
  ["效果", {"label":"what","jyutping":"haau6 gwo2","syntax":"abstract_np result_np","note":"result / effect; Cifu spoken top-2000 R3 lexical audit."}],
  ["文字", {"label":"what","jyutping":"man4 zi6","syntax":"object_np linguistic_term_np","note":"writing / script / characters; Cifu spoken top-2000 R3 lexical audit."}],
  ["圖", {"label":"what","jyutping":"tou4","syntax":"object_np visual_object_np","note":"diagram / picture / drawing; Cifu spoken top-2000 R3 lexical audit."}],
  ["銅", {"label":"what","jyutping":"tung4","syntax":"object_np material_np","note":"copper; Cifu spoken top-2000 R3 lexical audit."}],
  ["地標", {"label":"what","jyutping":"dei6 biu1","syntax":"object_np landmark_np","note":"landmark; Cifu spoken top-2000 R3 lexical audit."}],
  ["皮", {"label":"what","jyutping":"pei4","syntax":"object_np material_or_body_np","note":"skin / leather; Cifu spoken top-2000 R3 lexical audit."}],
  ["鬼", {"label":"what","jyutping":"gwai2","syntax":"object_np animate_np","note":"ghost; Cifu spoken top-2000 R3 lexical audit."}],
  ["電腦", {"label":"what","jyutping":"din6 nou5","syntax":"object_np device_np","note":"computer; Cifu spoken top-2000 R3 lexical audit."}],
  ["英文", {"label":"what","jyutping":"jing1 man4","syntax":"object_np language_np","note":"English language; Cifu spoken top-2000 R3 lexical audit."}],
  ["經濟", {"label":"what","jyutping":"ging1 zai3","syntax":"abstract_np domain_np","note":"economy / economics; Cifu spoken top-2000 R3 lexical audit."}],
  ["理由", {"label":"what","jyutping":"lei5 jau4","syntax":"abstract_np reason_np","note":"reason / grounds / justification; Cifu spoken top-2000 R3 lexical audit."}],
  ["法律", {"label":"what","jyutping":"faat3 leot6","syntax":"abstract_np domain_np","note":"law; Cifu spoken top-2000 R3 lexical audit."}],

  // v0.5.227: Cifu spoken top-2000 R4 nominal lexical coverage.
  ["虛線", {"label":"what","jyutping":"heoi1 sin3","syntax":"object_np visual_line_np","note":"dotted line; Cifu spoken top-2000 R4 lexical audit."}],
  ["自由", {"label":"what","jyutping":"zi6 jau4","syntax":"abstract_np concept_np","note":"freedom / liberty; Cifu spoken top-2000 R4 lexical audit."}],
  ["直線", {"label":"what","jyutping":"zik6 sin3","syntax":"object_np visual_line_np","note":"straight line; Cifu spoken top-2000 R4 lexical audit."}],
  ["性", {"label":"what","jyutping":"sing3","syntax":"abstract_np property_np","note":"nature / property / sex; Cifu spoken top-2000 R4 lexical audit."}],
  ["關係", {"label":"what","jyutping":"gwaan1 hai6","syntax":"abstract_np relation_np","note":"relation / relationship; Cifu spoken top-2000 R4 lexical audit."}],
  ["生活", {"label":"what","jyutping":"sang1 wut6","syntax":"abstract_np life_np","note":"life / livelihood; Cifu spoken top-2000 R4 lexical audit."}],
  ["法", {"label":"what","jyutping":"faat3","syntax":"abstract_np method_or_law_np","note":"law / method / way; Cifu spoken top-2000 R4 lexical audit."}],
  ["方法", {"label":"what","jyutping":"fong1 faat3","syntax":"abstract_np method_np","note":"method / way / means; Cifu spoken top-2000 R4 lexical audit."}],
  ["圖案", {"label":"what","jyutping":"tou4 on3","syntax":"object_np visual_object_np","note":"design / pattern; Cifu spoken top-2000 R4 lexical audit."}],
  ["尾", {"label":"what","jyutping":"mei5","syntax":"object_np body_part_np","note":"tail / end; Cifu spoken top-2000 R4 lexical audit."}],
  ["意見", {"label":"what","jyutping":"ji3 gin3","syntax":"abstract_np opinion_np","note":"opinion / suggestion; Cifu spoken top-2000 R4 lexical audit."}],
  ["圖片", {"label":"what","jyutping":"tou4 pin3","syntax":"object_np visual_object_np","note":"image / picture / photograph; Cifu spoken top-2000 R4 lexical audit."}],
  ["辦法", {"label":"what","jyutping":"baan6 faat3","syntax":"abstract_np method_np","note":"means / method / way; Cifu spoken top-2000 R4 lexical audit."}],
  ["財政", {"label":"what","jyutping":"coi4 zing3","syntax":"abstract_np domain_np","note":"public finance / finances; Cifu spoken top-2000 R4 lexical audit."}],
  ["碑", {"label":"what","jyutping":"bei1","syntax":"object_np monument_np","note":"monument / stone tablet; Cifu spoken top-2000 R4 lexical audit."}],
  ["距離", {"label":"what","jyutping":"keoi5 lei4","syntax":"abstract_np distance_np","note":"distance; Cifu spoken top-2000 R4 lexical audit."}],
  ["概念", {"label":"what","jyutping":"koi3 nim6","syntax":"abstract_np concept_np","note":"concept / idea; Cifu spoken top-2000 R4 lexical audit."}],
  ["人權", {"label":"what","jyutping":"jan4 kyun4","syntax":"abstract_np rights_np","note":"human rights; Cifu spoken top-2000 R4 lexical audit."}],
  ["考試", {"label":"what","jyutping":"haau2 si3","syntax":"event_np assessment_np","note":"exam; Cifu spoken top-2000 R4 lexical audit."}],
  ["杏", {"label":"what","jyutping":"hang6","syntax":"object_np food_or_plant_np","note":"apricot; Cifu spoken top-2000 R4 lexical audit."}],
  ["格", {"label":"what","jyutping":"gaak3","syntax":"abstract_or_object_np pattern_np","note":"frame / style / pattern; Cifu spoken top-2000 R4 lexical audit."}],
  ["團", {"label":"what","jyutping":"tyun4","syntax":"collective_np object_np","note":"group / society / regiment; Cifu spoken top-2000 R4 lexical audit."}],
  ["頭", {"label":"what","jyutping":"tau4","syntax":"object_np body_part_np","note":"head; Cifu spoken top-2000 R4 lexical audit."}],
  ["意", {"label":"what","jyutping":"ji3","syntax":"abstract_np idea_or_intention_np","note":"idea / meaning / intention; Cifu spoken top-2000 R4 lexical audit."}],
];
