"use strict";

module.exports = [  // Verbs
  ["食", { label: "doing", jyutping: "sik6", syntax: "verb transitive_affordance chain_select_edible", note: "eat" }],
  ["切", { label: "doing", jyutping: "cit3", syntax: "verb action_verb transitive_affordance", note: "cut; added for the sourced 用嚟 function example and ordinary lexical coverage." }],
  ["畫", { label: "doing", jyutping: "waak6", syntax: "verb action_verb transitive_affordance", note: "draw / paint; verb reading corrected during the authorized Glossika Week 16 lexical audit." }],
  ["畫畫", { label: "doing", jyutping: "waak6 waa2", syntax: "verb action_verb", note: "draw pictures / do drawing; verb + picture reading." }],
  ["飲", { label: "doing", jyutping: "jam2", syntax: "verb transitive_affordance chain_select_drinkable", note: "drink" }],
  ["睇", { label: "doing", jyutping: "tai2", syntax: "verb transitive_affordance chain_select_perception", note: "look/read/watch" }],
  ["聽", { label: "doing", jyutping: "teng1", syntax: "verb", note: "listen/hear" }],
  ["講", { label: "doing", jyutping: "gong2", syntax: "verb transitive_affordance chain_select_discourse_content", note: "speak" }],
  ["問", { label: "doing", jyutping: "man6", syntax: "verb", note: "ask" }],
  ["答", { label: "doing", jyutping: "daap3", syntax: "verb", note: "answer" }],
  ["去", { label: "doing", jyutping: "heoi3", syntax: "movement_verb", note: "go" }],
  ["返", { label: "doing", jyutping: "faan1", syntax: "movement_verb", note: "return" }],
  ["嚟", { label: "doing", jyutping: "lai4", syntax: "movement_verb", note: "come" }],
  ["坐", { label: "doing", jyutping: "co5", syntax: "verb", note: "sit" }],
  ["企", { label: "doing", jyutping: "kei5", syntax: "verb", note: "stand" }],
  ["瞓", { label: "doing", jyutping: "fan3", syntax: "verb", note: "sleep" }],
  ["玩", { label: "doing", jyutping: "waan2", syntax: "verb", note: "play" }],
  ["買", { label: "doing", jyutping: "maai5", syntax: "verb", note: "buy" }],
  ["賣", { label: "doing", jyutping: "maai6", syntax: "verb", note: "sell" }],
  ["煮", { label: "doing", jyutping: "zyu2", syntax: "verb", note: "cook; lexicon/Jyutping cleanup for 煮飯 examples." }],
  ["解決", { label: "doing", jyutping: "gaai2 kyut3", syntax: "verb", note: "solve / resolve; lexicon/Jyutping cleanup for UI example diagnostics." }],
  ["攞", { label: "doing", jyutping: "lo2", syntax: "verb", note: "take" }],
  ["走", { label: "func", jyutping: "zau2", syntax: "verb_complement directional_result_complement", note: "away; result/directional complement after action verbs such as 攞走." }],
  ["鬧", { label: "doing", jyutping: "naau6", syntax: "verb transitive_social_action_verb", note: "scold / tell off" }],
  ["幫", { label: "doing", jyutping: "bong1", syntax: "verb help_benefactive_verb", note: "help / help someone do something." }],
  ["摘", { label: "doing", jyutping: "zaak6", syntax: "verb harvest_pick_verb", note: "pick / pluck, as in 摘芒果." }],
  ["畀", { label: "doing", jyutping: "bei2", syntax: "ditransitive_verb", note: "give" }],
  ["俾", { label: "doing", jyutping: "bei2", syntax: "ditransitive_verb orthographic_variant_bei", note: "give; common spelling variant of 畀" }],
  ["做", { label: "doing", jyutping: "zou6", syntax: "verb", note: "do" }],
  ["使", { label: "func", jyutping: "sai2", syntax: "modal_necessity", note: "need to / be necessary; positive arm of 使唔使 and the base predicate related to 唔使." }],
  ["洗", { label: "doing", jyutping: "sai2", syntax: "verb", note: "wash" }],
  ["沖", { label: "doing", jyutping: "cung1", syntax: "verb", note: "rinse / bathe" }],
  ["打", { label: "doing", jyutping: "daa2", syntax: "verb", note: "hit / play / call" }],
  ["放", { label: "doing", jyutping: "fong3", syntax: "verb", note: "release / finish school" }],
  ["曬", { label: "doing", jyutping: "saai3", syntax: "verb", note: "sun / expose to sun" }],
  ["默", { label: "doing", jyutping: "mak6", syntax: "verb", note: "dictate from memory" }],
  ["炒", { label: "doing", jyutping: "caau2", syntax: "verb", note: "fry / speculate" }],
  ["發", { label: "doing", jyutping: "faat3", syntax: "verb", note: "issue / break out" }],
  ["陪", { label: "doing", jyutping: "pui4", syntax: "verb", note: "accompany" }],
  ["叫", { label: "doing", jyutping: "giu3", syntax: "naming_or_calling_verb", note: "call / be named" }],
  ["覺得", { label: "doing", jyutping: "gok3 dak1", syntax: "cognition_opinion_predicate", note: "think / feel" }],
  ["以為", { label: "doing", jyutping: "ji5 wai4", syntax: "cognition_opinion_predicate belief_predicate mistaken_belief_predicate", note: "think / suppose, often with a mistaken or counterfactual expectation." }],
  ["認為", { label: "doing", jyutping: "jing6 wai4", syntax: "cognition_opinion_predicate belief_predicate", note: "consider / hold the view that" }],
  ["相信", { label: "doing", jyutping: "soeng1 seon3", syntax: "cognition_opinion_predicate belief_predicate", note: "believe / trust" }],
  ["懷疑", { label: "doing", jyutping: "waai4 ji4", syntax: "cognition_opinion_predicate belief_predicate", note: "doubt / suspect" }],
  ["真", { label: "like", jyutping: "zan1", syntax: "stative_predicate truth_stative", note: "true / real" }],
  ["諗", { label: "doing", jyutping: "nam2", syntax: "cognition_verb", note: "think / consider; visible role is doing, internal class is cognition" }],
  ["諗住", { label: "doing", jyutping: "nam2 zyu6", syntax: "intention_frame", note: "intend / plan to" }],
  ["知", { label: "doing", jyutping: "zi1", syntax: "cognition_verb", note: "know" }],
  ["唔知", { label: "doing", jyutping: "m4 zi1", syntax: "negative_cognition_predicate", note: "don't know" }],
  ["點知", { label: "how", jyutping: "dim2 zi1", syntax: "wh_cognition_question", note: "how do you know?" }],
  ["話", { label: "doing", jyutping: "waa6", syntax: "speech_reporting_verb", note: "say / report" }],
  ["試", { label: "doing", jyutping: "si3", syntax: "verb", note: "try" }],
  ["慶祝", { label: "doing", jyutping: "hing3 zuk1", syntax: "verb", note: "celebrate" }],
  ["約", { label: "doing", jyutping: "joek3", syntax: "verb", note: "arrange / invite" }],
  ["約埋", { label: "doing", jyutping: "joek3 maai4", syntax: "verb_particle_include_together", note: "arrange/include together" }],
  ["分", { label: "doing", jyutping: "fan1", syntax: "verb", note: "divide / split" }],
  ["平均分", { label: "doing", jyutping: "ping4 gwan1 fan1", syntax: "compound_verb", note: "split evenly" }],
  ["鍾意", { label: "like", jyutping: "zung1 ji3", syntax: "preference_predicate", note: "like / prefer" }],
  ["信", { label: "doing", jyutping: "seon3", syntax: "belief_verb", note: "believe / trust" }],
  ["一次", { label: "how", jyutping: "jat1 ci3", syntax: "frequency_quantity", note: "once" }],
  ["等", { label: "doing", jyutping: "dang2", syntax: "verb", note: "wait" }],
  ["記得", { label: "doing", jyutping: "gei3 dak1", syntax: "cognition_reminder_predicate", note: "remember" }],
  ["放心", { label: "func", jyutping: "fong3 sam1", syntax: "formula_discourse_unit", note: "don't worry" }],
  ["Book", { label: "doing", jyutping: "book1", syntax: "borrowed_verb transitive_affordance chain_select_bookable_resource", note: "book / reserve" }],
  ["廣東話", { label: "what", jyutping: "gwong2 dung1 waa2", syntax: "language_np object_np discourse_content", note: "Cantonese language." }],


  // v0.5.29: active-corpus lexicon and learner-role cleanup.
  // These are lexical/category entries only. Larger reusable constructions
  // such as 用嚟 purpose frames, subject-preserving modal clauses, 係時候
  // time-to-action frames, and change/result templates remain planned in the
  // append-only Peppa expected-behavior note instead of being patched here.
  ["故仔", { label: "what", jyutping: "gu3 zai2", syntax: "story_noun object_np", note: "colloquial story noun; prevents misleading 故/仔 unknown split in active corpus." }],
  ["花", { label: "what", jyutping: "faa1", syntax: "flower_noun object_np", note: "flower" }],
  ["第二個", { label: "what", jyutping: "dai6 ji6 go3", syntax: "object_np headless_choice_np ordinal_or_alternative_np", note: "another / other one in the checked choice context; ordinal versus alternative reading otherwise depends on context." }],
  ["第二", { label: "func", jyutping: "dai6 ji6", syntax: "ordinal_modifier sequence_modifier", note: "second; ordinal/sequence modifier before a classifier, not a how-many question word." }],
  ["本", { label: "measure_word", jyutping: "bun2", syntax: "classifier_book", note: "measure word / classifier for books." }],
  ["本書", { label: "what", jyutping: "bun2 syu1", syntax: "classifier_object_np affected_theme_np", note: "Reference entry for the transparent classifier-object phrase 本 + 書; tokenizer must preserve the classifier and noun as separate learner-visible tokens." }],
  ["架", { label: "measure_word", jyutping: "gaa3", syntax: "classifier_vehicle", note: "measure word / classifier for vehicles." }],
  ["部", { label: "measure_word", jyutping: "bou6", syntax: "classifier_vehicle_machine", note: "measure word / classifier for vehicles and machines." }],
  ["支", { label: "measure_word", jyutping: "zi1", syntax: "classifier_long_rigid pen_classifier", note: "classifier for long rigid objects such as pens." }],
  ["機", { label: "what", jyutping: "gei1", syntax: "machine_noun object_np head_noun", note: "machine or device; can be the visible noun head after 部." }],
  ["樣", { label: "measure_word", jyutping: "joeng6", syntax: "classifier_kind_item", note: "measure word / classifier for a kind/item, as in 有樣驚喜." }],
  ["塊", { label: "measure_word", jyutping: "faai3", syntax: "classifier_flat_piece", note: "measure word / classifier for flat pieces/slices." }],
  ["座", { label: "measure_word", jyutping: "zo6", syntax: "classifier_large_structure", note: "measure word / classifier for mountains, buildings, and large structures." }],
  ["條", { label: "measure_word", jyutping: "tiu4", syntax: "classifier_long_thin", note: "measure word / classifier for long thin things and rivers." }],
  ["圖書館", { label: "where", jyutping: "tou4 syu1 gun2", syntax: "place_np library_place", note: "library/place noun; prevents 書 from surfacing as an object inside 圖書館." }],
  ["度", { label: "func", jyutping: "dou6", syntax: "locative_postposition", note: "locative postposition after 喺 + place." }],
  ["借", { label: "doing", jyutping: "ze3", syntax: "verb borrow_verb", note: "borrow/lend; transitive verb in the library corpus lines." }],
  ["交", { label: "doing", jyutping: "gaau1", syntax: "verb hand_over_verb", note: "hand over / deliver; reviewed CP021B predicate profile." }],
  ["織", { label: "doing", jyutping: "zik1", syntax: "verb creation_verb", note: "knit / weave; reviewed CP021B predicate profile." }],
  ["冷", { label: "like", jyutping: "laang5", syntax: "nominal_modifier clothing_modifier", note: "woollen / sweater-forming modifier in 冷衫." }],
  ["厚", { label: "like", jyutping: "hau5", syntax: "stative_predicate nominal_modifier degreeable", note: "thick; modifier in a reviewed CP021B heavy-theme boundary." }],
  ["整理", { label: "doing", jyutping: "zing2 lei5", syntax: "verb organization_action", note: "organize / put in order; visible relative-clause predicate in a CP021B boundary." }],
  ["書展", { label: "where", jyutping: "syu1 zin2", syntax: "place_np event_location", note: "book fair; visible relative-clause location in a reviewed CP021B example." }],
  ["讚", { label: "doing", jyutping: "zaan3", syntax: "verb transitive_social_action_verb", note: "praise; predicate in a preserved CP020 passive example." }],
  ["之後", { label: "when", jyutping: "zi1 hau6", syntax: "temporal_connector", note: "after / afterwards." }],
  ["還", { label: "doing", jyutping: "waan4", syntax: "verb return_borrowed_item", note: "return a borrowed item." }],
  ["準時", { label: "when", jyutping: "zeon2 si4", syntax: "temporal_manner_adverb", note: "on time / punctually." }],
  ["叫做", { label: "doing", jyutping: "giu3 zou6", syntax: "naming_verb", note: "be called / named." }],
  ["Peppa", { label: "who", jyutping: "pe1 paa1", syntax: "proper_name_ascii", note: "ASCII proper name in active corpus; Jyutping-style placeholder avoids letter-level neutral noise." }],
  ["George", { label: "who", jyutping: "zo3 zi6", syntax: "proper_name_ascii", note: "ASCII proper name in active corpus; prevents letter-level neutral noise." }],
  ["Richard", { label: "who", jyutping: "lei5 caat3", syntax: "proper_name_ascii", note: "ASCII proper name in active corpus; Cantonese-name reading placeholder prevents letter-level neutral noise." }],
  ["細佬", { label: "who", jyutping: "sai3 lou2", syntax: "kinship_person_np", note: "younger brother." }],
  ["時候", { label: "when", jyutping: "si4 hau6", syntax: "time_np", note: "time / occasion; keeps 係時候 lines from splitting 時/候 before a future time-to-action template." }],
  ["早唞", { label: "func", jyutping: "zou2 tau2", syntax: "formula_discourse_unit goodnight_formula", note: "good night / rest early formula." }],
  ["入邊", { label: "where", jyutping: "jap6 bin1", syntax: "place_np interior_location", note: "inside / interior." }],
  ["入面", { label: "where", jyutping: "jap6 min6", syntax: "place_np interior_location", note: "inside / interior." }],
  ["保持", { label: "doing", jyutping: "bou2 ci4", syntax: "verb maintain_verb", note: "maintain / keep." }],
  ["安靜", { label: "like", jyutping: "on1 zing6", syntax: "stative_predicate degreeable quiet_property", note: "quiet; stative complement/predicate." }],
  ["綠色", { label: "like", jyutping: "luk6 sik1", syntax: "color_modifier stative_predicate degreeable", note: "green; color modifier/stative." }],
  ["紅色", { label: "like", jyutping: "hung4 sik1", syntax: "color_modifier stative_predicate degreeable", note: "red; color modifier/stative." }],
  ["掣", { label: "what", jyutping: "zai3", syntax: "object_np button_switch_noun", note: "button / switch." }],
  ["用", { label: "doing", jyutping: "jung6", syntax: "verb use_verb instrument_coverb", note: "use; as a preverbal coverb it can mark an instrument before an action predicate." }],
  ["寫", { label: "doing", jyutping: "se2", syntax: "verb write_verb", note: "write." }],
  ["字", { label: "what", jyutping: "zi6", syntax: "object_np writing_content_np", note: "characters / writing." }],
  ["泥氹", { label: "what", jyutping: "nai4 tam5", syntax: "object_np place_np puddle_noun", note: "mud puddle; object/place-capable noun." }],
  ["跳", { label: "doing", jyutping: "tiu3", syntax: "verb jump_verb", note: "jump." }],
  ["水喉", { label: "what", jyutping: "seoi2 hau4", syntax: "object_np tap_noun", note: "water tap / faucet." }],
  ["露營車", { label: "what", jyutping: "lou6 jing4 ce1", syntax: "vehicle_np object_np topic_np", note: "camper van / caravan." }],
  ["帶", { label: "doing", jyutping: "daai3", syntax: "verb take_bring_verb", note: "take / bring." }],
  ["度假", { label: "doing", jyutping: "dou6 gaa3", syntax: "verb vacation_verb", note: "go on holiday / vacation." }],
  ["請", { label: "func", jyutping: "cing2", syntax: "politeness_imperative_marker", note: "please; polite imperative marker." }],
  ["沿住", { label: "func", jyutping: "jyun4 zyu6", syntax: "path_coverb", note: "along / following a path." }],
  ["公路", { label: "where", jyutping: "gung1 lou6", syntax: "place_np path_np road_noun", note: "road / highway." }],
  ["直行", { label: "doing", jyutping: "zik6 haang4", syntax: "verb motion_verb go_straight", note: "go straight." }],
  ["係咪", { label: "func", jyutping: "hai6 mai6", syntax: "yes_no_question_marker", note: "is it / whether; yes-no question marker." }],
  ["蕩失路", { label: "doing", jyutping: "dong6 sat1 lou6", syntax: "verb get_lost_idiom", note: "get lost." }],
  ["爹哋", { label: "who", jyutping: "de1 di6", syntax: "kinship_person_np", note: "daddy / father." }],
  ["驚喜", { label: "what", jyutping: "ging1 hei2", syntax: "object_np surprise_noun abstract_np", note: "surprise." }],
  ["最", { label: "how", jyutping: "zeoi3", syntax: "degree_superlative", note: "most; superlative degree adverb." }],
  ["叻", { label: "like", jyutping: "lek1", syntax: "stative_predicate degreeable skillful_property", note: "clever / skillful / good at." }],
  ["地圖", { label: "what", jyutping: "dei6 tou4", syntax: "object_np map_noun", note: "map." }],
  ["已經", { label: "when", jyutping: "ji5 ging1", syntax: "temporal_adverb perfective_temporal", note: "already." }],
  ["到達", { label: "doing", jyutping: "dou3 daat6", syntax: "verb arrive_reach_verb", note: "arrive / reach." }],
  ["目的地", { label: "where", jyutping: "muk6 dik1 dei6", syntax: "place_np goal_place destination_noun", note: "destination." }],
  ["野餐", { label: "doing", jyutping: "je5 caan1", syntax: "verb picnic_verb", note: "have a picnic." }],
  ["豬先生", { label: "who", jyutping: "zyu1 sin1 saang1", syntax: "personified_name_title_np", note: "Mr Pig; personified character name/title." }],
  ["喺度", { label: "func", jyutping: "hai2 dou6", syntax: "progressive_or_locative_marker", note: "at here / progressive marker depending context." }],
  ["整", { label: "doing", jyutping: "zing2", syntax: "verb make_fix_verb", note: "make / fix / repair." }],
  ["蔬菜湯", { label: "what", jyutping: "so1 coi3 tong1", syntax: "food_np soup_noun object_np", note: "vegetable soup." }],
  ["午餐", { label: "what", jyutping: "ng5 caan1", syntax: "meal_np food_np object_np", note: "lunch." }],
  ["蔬果皮", { label: "what", jyutping: "so1 gwo2 pei4", syntax: "object_np compostable_food_peels", note: "fruit/vegetable peels." }],
  ["堆肥", { label: "what", jyutping: "deoi1 fei4", syntax: "object_np compost_noun", note: "compost." }],
  ["營養", { label: "what", jyutping: "jing4 joeng5", syntax: "abstract_np nutrition_noun", note: "nutrition; in 有營養 = nutritious." }],
  ["泥土", { label: "what", jyutping: "nai4 tou2", syntax: "object_np soil_noun", note: "soil." }],
  ["香蕉皮", { label: "what", jyutping: "hoeng1 ziu1 pei4", syntax: "object_np banana_peel_noun", note: "banana peel." }],
  ["幫助", { label: "doing", jyutping: "bong1 zo6", syntax: "verb help_verb", note: "help." }],
  ["植物", { label: "what", jyutping: "zik6 mat6", syntax: "object_np plant_noun", note: "plant." }],
  ["生長", { label: "doing", jyutping: "sang1 zoeng2", syntax: "verb grow_verb", note: "grow." }],
  ["蟲蟲", { label: "what", jyutping: "cung4 cung2", syntax: "animal_np object_np bug_noun", note: "bug/wormy creature; animals remain learner role what unless personification is later promoted." }],
  ["將", { label: "func", jyutping: "zoeng1", syntax: "disposal_coverb", note: "disposal/handling coverb 將 + object + predicate." }],
  ["搵", { label: "doing", jyutping: "wan2", syntax: "verb find_verb", note: "find / look for." }],
  ["轆", { label: "doing", jyutping: "luk1", syntax: "verb swipe_card_verb", note: "swipe, as in 轆咭; source-linked bounded action use." }],
  ["咭", { label: "what", jyutping: "kaat1", syntax: "object_np card_noun", note: "card; Hong Kong written variant in 轆咭." }],
  ["蘋果芯", { label: "what", jyutping: "ping4 gwo2 sam1", syntax: "object_np apple_core_noun", note: "apple core." }],
  ["掉落", { label: "doing", jyutping: "diu6 lok6", syntax: "verb drop_into_down", note: "drop / put down / fall down; contextually drop into a bin." }],
  ["堆肥箱", { label: "what", jyutping: "deoi1 fei4 soeng1", syntax: "container_np object_np compost_bin_noun", note: "compost bin." }],
  ["蚯蚓", { label: "what", jyutping: "jau1 jan5", syntax: "animal_np object_np earthworm_noun", note: "earthworm." }],
  ["睡房", { label: "where", jyutping: "seoi6 fong2", syntax: "place_np room_place bedroom_noun", note: "bedroom." }],
  ["變成", { label: "doing", jyutping: "bin3 sing4", syntax: "verb change_into_verb", note: "become / turn into." }],
  ["變", { label: "doing", jyutping: "bin3", syntax: "verb change_verb", note: "change / become; future change-result templates should keep 變+咗 transparent." }],
  ["恐龍天地", { label: "what", jyutping: "hung2 lung4 tin1 dei6", syntax: "compound_np dinosaur_world object_np", note: "dinosaur world; story-specific compound noun." }],
  ["恐龍", { label: "what", jyutping: "hung2 lung4", syntax: "animal_toy_np object_np dinosaur_noun", note: "dinosaur." }],
  ["火車", { label: "what", jyutping: "fo2 ce1", syntax: "vehicle_toy_np object_np train_noun", note: "train." }],
  ["冧", { label: "doing", jyutping: "lam3", syntax: "verb result_collapse_verb", note: "collapse / knock down; appears in 整冧咗." }],
  ["屋", { label: "what", jyutping: "uk1", syntax: "object_np house_noun", classifier_classes: ["building_shop"], note: "house." }],
  ["嘈", { label: "like", jyutping: "cou4", syntax: "stative_predicate degreeable noisy_property", note: "noisy." }],
  ["靜", { label: "like", jyutping: "zing6", syntax: "stative_predicate degreeable quiet_property", note: "quiet; property predicate in location-framed clauses such as 屋企好靜." }],
  ["擺", { label: "doing", jyutping: "baai2", syntax: "verb action_verb positioning_verb", note: "put / place; placement predicate in locative-inversion structures." }],
  ["玩具籃", { label: "what", jyutping: "wun6 geoi6 laam4", syntax: "container_np object_np toy_basket_noun", note: "toy basket." }],
  ["火山", { label: "what", jyutping: "fo2 saan1", syntax: "place_object_np volcano_noun", note: "volcano." }],
  ["積木", { label: "what", jyutping: "zik1 muk6", syntax: "object_np blocks_noun", note: "building blocks." }],
  ["河", { label: "where", jyutping: "ho4", syntax: "place_np river_noun", note: "river; place-like object in the toy-room transformation line." }],
  ["醫院", { label: "where", jyutping: "ji1 jyun2", syntax: "place_np hospital_noun", note: "hospital/place noun." }],
  ["一定", { label: "how", jyutping: "jat1 ding6", syntax: "certainty_adverb", note: "definitely / certainly; premodal certainty adverb." }],
  ["上床", { label: "doing", jyutping: "soeng5 cong4", syntax: "verb get_into_bed", note: "go/get into bed." }],
  ["休息", { label: "doing", jyutping: "jau1 sik1", syntax: "verb rest_verb", note: "rest." }],
  ["出邊", { label: "where", jyutping: "ceot1 bin1", syntax: "place_np outside_location", note: "outside." }],
  ["停", { label: "doing", jyutping: "ting4", syntax: "verb stop_verb", note: "stop." }],
  ["雨", { label: "what", jyutping: "jyu5", syntax: "weather_np rain_noun weather_phenomenon environmental_phenomenon object_np", note: "rain; a visible weather-phenomenon component in 落雨." }],
  ["風", { label: "what", jyutping: "fung1", syntax: "weather_np wind_noun weather_phenomenon environmental_phenomenon", note: "wind; a visible weather-phenomenon component in 打風." }],
  ["天光", { label: "doing", jyutping: "tin1 gwong1", syntax: "environmental_transition_predicate daylight_transition_predicate impersonal_predicate", note: "daybreak / become light; a genuinely subjectless environmental transition predicate." }],
  ["花園", { label: "where", jyutping: "faa1 jyun2", syntax: "place_np garden_noun", note: "garden." }],
  ["通常", { label: "when", jyutping: "tung1 soeng4", syntax: "habitual_frequency_adverb", note: "usually." }],

  // v0.5.227: source-audited high-frequency lexical coverage.
  ["知道", {"label":"doing","jyutping":"zi1 dou3","syntax":"cognition_verb","note":"know / be aware of; Cifu spoken top-2000 R1 lexical audit."}],
  ["繼續", {"label":"doing","jyutping":"gai3 zuk6","syntax":"verb","note":"continue / proceed; Cifu spoken top-2000 R1 lexical audit."}],
  ["恨", {"label":"doing","jyutping":"han6","syntax":"verb attitude_verb","note":"hate / regret / long for; Cifu spoken top-2000 R1 lexical audit."}],
  ["交叉", {"label":"doing","jyutping":"gaau1 caa1","syntax":"verb","note":"cross / intersect; Cifu spoken top-2000 R1 lexical audit."}],
];
